// components/shared/StatCounter.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { classNames } from '@/lib/cx';
import styles from '@/styles/StatCounter.module.css';

const cx = classNames(styles);

export interface StatCounterProps {
  value: number;
  label: string;
  suffix?: string;
  compact?: boolean;
}

/** Counts up to `value` the first time the element scrolls into view. */
export function StatCounter({ value, label, suffix = '', compact = false }: StatCounterProps) {
  const host = useRef<HTMLDivElement>(null);
  const [display, setDisplay] = useState(0);

  useEffect(() => {
    const element = host.current;
    if (!element) return;

    if (matchMedia('(prefers-reduced-motion: reduce)').matches) {
      setDisplay(value);
      return;
    }

    let frame = 0;
    const animate = () => {
      const started = performance.now();
      const tick = (now: number) => {
        const progress = Math.min((now - started) / 1100, 1);
        setDisplay(Math.round(value * (1 - Math.pow(1 - progress, 3))));
        if (progress < 1) frame = requestAnimationFrame(tick);
      };
      frame = requestAnimationFrame(tick);
    };

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (!entry.isIntersecting) return;
        animate();
        observer.disconnect();
      },
      { threshold: 0.5 }
    );
    observer.observe(element);

    return () => {
      observer.disconnect();
      cancelAnimationFrame(frame);
    };
  }, [value]);

  return (
    <div ref={host} className={cx('host', compact && 'compact')}>
      <strong>{display}{suffix}</strong>
      <span>{label}</span>
    </div>
  );
}

// src/app/pages/landing/stat-counter.component.ts
import { AfterViewInit, Component, ElementRef, Input, OnDestroy } from '@angular/core';

@Component({
  selector: 'so-stat-counter',
  standalone: true,
  template: `<strong>{{display}}{{suffix}}</strong><span>{{label}}</span>`,
  styles: [`
    :host{display:block;padding:0 34px;border-left:1px solid #dfe5ef}
    strong{display:block;color:#10213d;font-size:clamp(38px,4vw,66px);font-weight:650;letter-spacing:-.065em;line-height:1}
    span{display:block;margin-top:12px;color:#68758a;font-size:13px;line-height:1.45}
    @media(max-width:700px){:host{padding:24px 0;border-left:0;border-top:1px solid #dfe5ef}}
  `]
})
export class StatCounterComponent implements AfterViewInit, OnDestroy {
  @Input({ required: true }) value = 0;
  @Input() suffix = '';
  @Input({ required: true }) label = '';
  display = 0;
  private observer?: IntersectionObserver;
  private frame = 0;

  constructor(private readonly host: ElementRef<HTMLElement>) {}

  ngAfterViewInit(): void {
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) {
      this.display = this.value;
      return;
    }
    this.observer = new IntersectionObserver(([entry]) => {
      if (!entry.isIntersecting) return;
      this.animate();
      this.observer?.disconnect();
    }, { threshold: .5 });
    this.observer.observe(this.host.nativeElement);
  }

  private animate(): void {
    const started = performance.now();
    const tick = (now: number) => {
      const progress = Math.min((now - started) / 1100, 1);
      this.display = Math.round(this.value * (1 - Math.pow(1 - progress, 3)));
      if (progress < 1) this.frame = requestAnimationFrame(tick);
    };
    this.frame = requestAnimationFrame(tick);
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
    cancelAnimationFrame(this.frame);
  }
}
