// src/app/pages/student-portal/academic-information.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { StudentProfileUiStore } from './student-profile-ui.store';
import { EduField, Qualification } from './education-options';
import { AuthApiService } from '../../core/auth-api.service';

@Component({
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  styleUrl: './academic-information.css',
  template: `
    <section class="step-page">
      <div class="profile-form-card" *ngIf="!loaded">
        <p>Loading…</p>
      </div>

      <form class="profile-form-card" [formGroup]="form" (ngSubmit)="saveAndContinue()" *ngIf="loaded">
        <div class="card-head">
          <div class="placeholder-copy">
            <div>
              <h2>Academic Information details</h2>
              <p>Your information is securely saved to your student profile.</p>
            </div>
          </div>
          <span class="step-badge">STEP 3 OF 9</span>
        </div>

        <div class="qualification-question">
          <h2>Select your appropriate qualification(s) <span class="required-mark">*</span></h2>
          <div class="qualification-grid">
            <button type="button" class="qualification-card" *ngFor="let lvl of levels"
              [class.selected]="isSelected(lvl)" (click)="toggleLevel(lvl)">
              <span class="qual-check">✓</span>
              <strong>{{lvl}}</strong>
            </button>
          </div>
          <small class="field-error" *ngIf="showSelectionError()">Select at least one qualification</small>
        </div>

        <div class="reveal-section" [class.open]="selectedLevels().length">
          <div class="level-section" *ngFor="let lvl of selectedLevels(); trackBy: trackByLevel">
            <h3 class="section-title">{{lvl}} details</h3>
            <div class="dynamic-fields" [formGroup]="levelGroup(lvl)">
              <ng-container *ngFor="let f of fieldsFor(lvl); trackBy: trackByField">
                <label [class.wide]="f.wide" [class.field-invalid]="showLevelFieldError(lvl, f.key)">
                  <span class="field-label">{{f.label}} <span class="required-mark">*</span></span>
                  <select *ngIf="f.type==='select' && !f.allowCustom" [formControlName]="f.key" (blur)="markLevelFieldTouched(lvl, f.key)">
                    <option value="" disabled>Select {{f.label}}</option>
                    <option *ngFor="let opt of f.options" [value]="opt">{{opt}}</option>
                  </select>
                  <ng-container *ngIf="f.type==='select' && f.allowCustom">
                    <input type="text" [attr.list]="lvl+'-'+f.key+'-list'" [formControlName]="f.key" placeholder="Select or type your own" (blur)="markLevelFieldTouched(lvl, f.key)">
                    <datalist [id]="lvl+'-'+f.key+'-list'">
                      <option *ngFor="let opt of f.options" [value]="opt"></option>
                    </datalist>
                  </ng-container>
                  <input *ngIf="f.type==='text'" type="text" [formControlName]="f.key" [placeholder]="f.placeholder || ''" (blur)="markLevelFieldTouched(lvl, f.key)">
                  <input *ngIf="f.type==='number'" type="number" min="0" [formControlName]="f.key" [placeholder]="f.placeholder || ''" (blur)="markLevelFieldTouched(lvl, f.key)">
                  <small class="field-error" *ngIf="showLevelFieldError(lvl, f.key)">This field is required</small>
                </label>
              </ng-container>
            </div>
          </div>

          <ng-container *ngIf="selectedLevels().length && hasAboveSchoolLevel()">
            <h3 class="section-title">Do you have an education gap?</h3>
            <div class="field-grid">
              <label class="wide">
                <select formControlName="educationGap">
                  <option value="" disabled>Select</option>
                  <option *ngFor="let g of educationGapOptions" [value]="g">{{g}}</option>
                </select>
              </label>
            </div>
          </ng-container>
        </div>

        <p class="save-message error" *ngIf="submitted && (form.invalid || !selectedLevels().length)">Please fix the highlighted fields before continuing.</p>
        <p class="save-message error" *ngIf="saveError">{{saveError}}</p>
      </form>

      <div class="step-actions">
        <a class="button secondary" routerLink="/student/study-preferences">Previous</a>
        <button class="button primary" type="button" [disabled]="saving || !loaded" (click)="saveAndContinue()">{{saving ? 'Saving…' : 'Continue'}}</button>
      </div>
    </section>
  `
})
export class AcademicInformationComponent implements OnInit {
  loaded = false;
  levels: Qualification[] = [];
  educationGapOptions: string[] = [];
  qualificationFields: Record<string, EduField[]> = {};

  submitted = false;
  selected: Partial<Record<Qualification, boolean>> = {};

  form!: FormGroup;

  saving = false;
  saveError = '';

  private returnToReview = false;

  constructor(
    private fb: FormBuilder,
    public store: StudentProfileUiStore,
    private router: Router,
    private route: ActivatedRoute,
    private api: AuthApiService,
    private cdr: ChangeDetectorRef
  ) {
    this.returnToReview = this.route.snapshot.queryParamMap.get('from') === 'review';
  }

  private getToken(): string | null {
    return localStorage.getItem('superoffer_access_token') || sessionStorage.getItem('superoffer_access_token');
  }

  private handleUnauthorized() {
    localStorage.removeItem('superoffer_access_token');
    sessionStorage.removeItem('superoffer_access_token');
    this.router.navigate(['/auth/login/student'], { queryParams: { sessionExpired: '1' } });
  }

  /** Reconstructs the same field-set-per-qualification-level structure that used to be
   *  hardcoded, but built from the option lists fetched from the backend. */
  private buildQualificationFields(curriculumOptions: string[], educationYears: string[], universityOptions: string[]): Record<string, EduField[]> {
    const cgpaField: EduField = { key: 'cgpa', label: 'CGPA / Percentage', type: 'text', placeholder: 'e.g. 8.7 CGPA or 85%' };
    const backlogsField: EduField = { key: 'backlogs', label: 'Number of Backlogs', type: 'number', placeholder: 'e.g. 0' };
    const startedYearField: EduField = { key: 'startedYear', label: 'Started Year', type: 'select', options: educationYears };
    const completionYearField: EduField = { key: 'completionYear', label: 'Completion Year', type: 'select', options: educationYears };
    const yearsOfEducationField: EduField = { key: 'yearsOfEducation', label: 'Years of Education', type: 'number', placeholder: 'e.g. 10' };
    const curriculumField: EduField = { key: 'curriculum', label: 'Curriculum', type: 'select', options: curriculumOptions };

    return {
      '11th': [curriculumField, cgpaField, startedYearField, completionYearField],
      '12th': [curriculumField, cgpaField, startedYearField, completionYearField],
      Diploma: [
        { key: 'institutionName', label: 'College Name', type: 'text', placeholder: 'e.g. Government Polytechnic College', wide: true },
        { key: 'specialization', label: 'Specialization', type: 'text', placeholder: 'e.g. Mechanical Engineering' },
        cgpaField, backlogsField, startedYearField, completionYearField
      ],
      "Bachelor's Degree": [
        { key: 'degreeName', label: 'Degree Name', type: 'text', placeholder: 'e.g. B.Tech, B.Sc, B.Com' },
        { key: 'specialization', label: 'Specialization / Major', type: 'text', placeholder: 'e.g. Computer Science' },
        { key: 'institutionName', label: 'University / College Name', type: 'select', options: universityOptions, wide: true, allowCustom: true },
        cgpaField, backlogsField, startedYearField, completionYearField, yearsOfEducationField
      ],
      "Master's Degree": [
        { key: 'degreeName', label: 'Degree Name', type: 'text', placeholder: 'e.g. M.Tech, M.Sc, MBA' },
        { key: 'specialization', label: 'Specialization', type: 'text', placeholder: 'e.g. Data Science' },
        { key: 'institutionName', label: 'University Name', type: 'select', options: universityOptions, wide: true, allowCustom: true },
        cgpaField, backlogsField, startedYearField, completionYearField, yearsOfEducationField
      ],
      PhD: [
        { key: 'degreeName', label: 'Degree Name', type: 'text', placeholder: 'e.g. PhD in Computer Science' },
        { key: 'specialization', label: 'Research Area', type: 'text', placeholder: 'e.g. Machine Learning' },
        { key: 'institutionName', label: 'University Name', type: 'select', options: universityOptions, wide: true, allowCustom: true },
        cgpaField, backlogsField, startedYearField, completionYearField, yearsOfEducationField
      ]
    };
  }

  async ngOnInit() {
    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }

    try {
      const options = await this.api.getAcademicInformationReferenceData();
      this.levels = options.qualificationOptions as Qualification[];
      this.educationGapOptions = options.educationGapOptions;
      this.qualificationFields = this.buildQualificationFields(options.curriculumOptions, options.educationYears, options.universityOptions);
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        this.handleUnauthorized();
        return;
      }
      // Reference data unreachable — fall back to an empty qualification list; the student can retry later.
    }

    this.form = this.fb.nonNullable.group({
      levels: this.fb.nonNullable.group(
        Object.fromEntries(this.levels.map(level => [level, this.buildLevelGroup(level)]))
      ),
      educationGap: this.fb.nonNullable.control<string>('')
    });
    this.loaded = true;

    try {
      const profile = await this.api.studentProfile(token);
      const academic = (profile?.academic as { history?: Array<Record<string, string>>; educationGap?: string }) || {};
      const history = academic.history || [];
      if (!this.selectedLevels().length && history.length) {
        for (const entry of history) {
          const level = entry['level'] as Qualification;
          if (!this.levels.includes(level)) continue;
          this.toggleLevel(level);
          const group = this.levelGroup(level);
          for (const f of this.fieldsFor(level)) {
            if (entry[f.key] !== undefined) group.get(f.key)!.setValue(entry[f.key]);
          }
        }
        if (academic.educationGap) this.form.get('educationGap')!.setValue(academic.educationGap);
      }
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        this.handleUnauthorized();
        return;
      }
      // No saved academic info yet, or the server is unreachable — the student can still fill the form from scratch.
    }
    this.cdr.detectChanges();
  }

  private buildLevelGroup(level: Qualification): FormGroup {
    return this.fb.nonNullable.group(
      Object.fromEntries(this.qualificationFields[level].map(f => [f.key, this.fb.nonNullable.control<string>('')]))
    );
  }

  get levelsGroup(): FormGroup { return this.form.get('levels') as FormGroup; }
  levelGroup(level: Qualification): FormGroup { return this.levelsGroup.get(level) as FormGroup; }
  fieldsFor(level: Qualification): EduField[] { return this.qualificationFields[level]; }

  isSelected(level: Qualification): boolean { return !!this.selected[level]; }
  selectedLevels(): Qualification[] { return this.levels.filter(lvl => this.selected[lvl]); }
  hasAboveSchoolLevel(): boolean { return this.selectedLevels().some(lvl => lvl !== '11th' && lvl !== '12th'); }

  toggleLevel(level: Qualification) {
    const nowSelected = !this.selected[level];
    this.selected[level] = nowSelected;
    const group = this.levelGroup(level);
    this.qualificationFields[level].forEach(f => {
      const control = group.get(f.key)!;
      if (nowSelected) {
        control.setValidators(Validators.required);
      } else {
        control.setValidators(null);
        control.setValue('');
        control.markAsUntouched();
      }
      control.updateValueAndValidity({ emitEvent: false });
    });
  }

  trackByLevel(index: number, level: Qualification): string { return level; }
  trackByField(index: number, field: EduField): string { return field.key; }

  markLevelFieldTouched(level: Qualification, key: string) { this.levelGroup(level).get(key)!.markAsTouched(); }

  showLevelFieldError(level: Qualification, key: string): boolean {
    const control = this.levelGroup(level).get(key)!;
    return (control.touched || this.submitted) && control.invalid;
  }

  showSelectionError(): boolean {
    return this.submitted && !this.selectedLevels().length;
  }

  async saveAndContinue() {
    this.submitted = true;
    this.saveError = '';
    this.form.markAllAsTouched();
    if (this.form.invalid || !this.selectedLevels().length) return;

    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }

    const value = this.form.getRawValue();
    const selected = this.selectedLevels();
    const highest = selected[selected.length - 1];
    const highestFields = value.levels[highest] as Record<string, string>;

    const institution = highestFields['institutionName'] || this.store.values['institution'] || '';
    const score = highestFields['cgpa'] || this.store.values['score'] || '';
    const graduationYear = highestFields['completionYear'] || this.store.values['graduationYear'] || '';
    const degreeSummary = [highestFields['degreeName'], highestFields['specialization']].filter(Boolean).join(' ');
    const qualification = degreeSummary || highest || this.store.values['qualification'] || '';
    const history = selected.map(level => ({ level, ...(value.levels[level] as Record<string, string>) }));

    const payload = {
      qualificationLevel: highest,
      institution,
      score,
      graduationYear,
      qualification,
      educationGap: value.educationGap || undefined,
      history
    };

    this.saving = true;
    try {
      await this.api.saveStudentAcademicInformation(token, payload);

      this.store.values['qualificationLevel'] = highest;
      Object.assign(this.store.values, highestFields);
      this.store.values['educationGap'] = value.educationGap;
      this.store.values['institution'] = institution;
      this.store.values['score'] = score;
      this.store.values['graduationYear'] = graduationYear;
      this.store.values['qualification'] = qualification;
      this.store.values['academicHistory'] = JSON.stringify(history);

      this.router.navigateByUrl(this.returnToReview ? '/student/review' : '/student/english-exam');
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        this.handleUnauthorized();
        return;
      }
      this.saveError = e instanceof Error ? e.message : 'Could not save your academic details. Please try again.';
    } finally {
      this.saving = false;
      this.cdr.detectChanges();
    }
  }
}

// components/student/AcademicInformation.tsx
'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { authApi, type ApiError } from '@/lib/api/auth-api';
import { classNames } from '@/lib/cx';
import type { Qualification } from '@/lib/options/education';
import { clearAccessToken, readAccessToken } from '@/lib/storage';
import { useCompositeRows } from '@/lib/forms/use-composite-rows';
import { useSectionFields } from '@/lib/forms/use-section-fields';
import type { FormFieldDef } from '@/lib/forms/use-form-schema';
import { useSchemaExtras } from '@/lib/forms/use-schema-extras';
import { useStudentProfile } from '@/lib/stores/student-profile.store';
import styles from '@/styles/AcademicInformation.module.css';
import { SchemaFields } from './SchemaFields';

const cx = classNames(styles);

type LevelValues = Record<string, Record<string, string>>;

/**
 * Reconstructs the same field-set-per-qualification-level structure that used to be
 * hardcoded, but built from the option lists fetched from the backend.
 */
/** The keys this step draws itself; anything else published is an addition. */
const ACADEMIC_CODED = ['history', 'educationGap', 'qualificationLevel', 'institution', 'score', 'graduationYear', 'qualification'];

export function AcademicInformation() {
  const profile = useStudentProfile();

  /** Fields this step draws by hand; anything else the schema declares is added below. */
  const extras = useSchemaExtras(
    'academicInformation',
    ACADEMIC_CODED,
    profile.profile.academic,
    profile.loaded
  );

  const router = useRouter();
  const searchParams = useSearchParams();
  const returnToReview = searchParams.get('from') === 'review';

  const [loaded, setLoaded] = useState(false);
  const [levels, setLevels] = useState<Qualification[]>([]);
  const [educationGapOptions, setEducationGapOptions] = useState<string[]>([]);
  /**
   * What each academic row asks for comes from the published form, keyed on the
   * qualification level of the row itself. How many rows there are still comes
   * from which levels the student ticked.
   */
  const rows = useCompositeRows('academicInformation', 'history');

  /** The section's own title and the fields it draws by hand, as published. */
  const fields = useSectionFields('academicInformation', ACADEMIC_CODED);

  const [selected, setSelected] = useState<Partial<Record<Qualification, boolean>>>({});
  const [levelValues, setLevelValues] = useState<LevelValues>({});
  const [educationGap, setEducationGap] = useState('');
  const [fieldTouched, setFieldTouched] = useState<Record<string, boolean>>({});
  const [submitted, setSubmitted] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');

  const handleUnauthorized = () => {
    clearAccessToken();
    router.push('/auth/login/student?sessionExpired=1');
  };

  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      const token = readAccessToken();
      if (!token) {
        router.push('/auth/login/student');
        return;
      }

      let levelList: Qualification[] = [];
      try {
        const options = await authApi.getAcademicInformationReferenceData();
        if (cancelled) return;
        levelList = options.qualificationOptions as Qualification[];
        setLevels(levelList);
        setEducationGapOptions(options.educationGapOptions);
      } catch (e) {
        if ((e as ApiError).status === 401) {
          handleUnauthorized();
          return;
        }
        // Reference data unreachable — fall back to an empty qualification list; the student can retry later.
      }
      setLoaded(true);

      try {
        const profile = await authApi.studentProfile(token);
        if (cancelled) return;
        const academic = (profile?.academic as { history?: Array<Record<string, string>>; educationGap?: string }) || {};
        const history = academic.history || [];
        if (history.length) {
          const nextSelected: Partial<Record<Qualification, boolean>> = {};
          const nextValues: LevelValues = {};
          for (const entry of history) {
            const level = entry['level'] as Qualification;
            if (!levelList.includes(level)) continue;
            nextSelected[level] = true;
            /** Every saved value is kept, including fields an admin added later. */
            nextValues[level] = {};
            for (const [key, value] of Object.entries(entry)) {
              if (key !== 'level' && value !== undefined) nextValues[level][key] = String(value);
            }
          }
          setSelected(current => (Object.keys(current).length ? current : nextSelected));
          setLevelValues(current => (Object.keys(current).length ? current : nextValues));
          if (academic.educationGap) setEducationGap(academic.educationGap);
        }
      } catch (e) {
        if ((e as ApiError).status === 401) {
          handleUnauthorized();
          return;
        }
        // No saved academic info yet, or the server is unreachable — the student can still fill the form from scratch.
      }
    };

    void load();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const fieldsFor = (level: Qualification) => rows.forRow({ level, ...(levelValues[level] || {}) });
  const isSelected = (level: Qualification) => !!selected[level];
  const selectedLevels = (): Qualification[] => levels.filter(level => selected[level]);
  const hasAboveSchoolLevel = () => selectedLevels().some(level => level !== '11th' && level !== '12th');

  const valueOf = (level: Qualification, key: string) => levelValues[level]?.[key] ?? '';

  const setFieldValue = (level: Qualification, key: string, value: string) =>
    setLevelValues(current => ({ ...current, [level]: { ...(current[level] || {}), [key]: value } }));

  const toggleLevel = (level: Qualification) => {
    setSelected(current => ({ ...current, [level]: !current[level] }));
    setLevelValues(current => {
      if (!current[level]) return { ...current, [level]: {} };
      const next = { ...current };
      next[level] = {};
      return next;
    });
  };

  const markLevelFieldTouched = (level: Qualification, key: string) =>
    setFieldTouched(current => ({ ...current, [`${level}.${key}`]: true }));

  const showLevelFieldError = (level: Qualification, key: string) =>
    (fieldTouched[`${level}.${key}`] || submitted) && !valueOf(level, key).trim();

  const showSelectionError = () => submitted && !selectedLevels().length;

  const formInvalid = selectedLevels().some(level =>
    !!rows.missingIn({ level, ...(levelValues[level] || {}) }).length);

  const saveAndContinue = async () => {
    setSubmitted(true);
    extras.touchAll();
    setSaveError('');
    if (formInvalid || !selectedLevels().length) return;

    const token = readAccessToken();
    if (!token) {
      router.push('/auth/login/student');
      return;
    }

    const selectedList = selectedLevels();
    const highest = selectedList[selectedList.length - 1];
    const highestFields = levelValues[highest] || {};

    const institution = highestFields['institutionName'] || '';
    const score = highestFields['cgpa'] || '';
    const graduationYear = highestFields['completionYear'] || '';
    const degreeSummary = [highestFields['degreeName'], highestFields['specialization']].filter(Boolean).join(' ');
    const qualification = degreeSummary || highest || '';
    const history = selectedList.map(level => ({ level, ...(levelValues[level] || {}) }));

    const payload = {
      ...extras.values0,
      qualificationLevel: highest,
      institution,
      score,
      graduationYear,
      qualification,
      educationGap: educationGap || undefined,
      history
    };

    setSaving(true);
    try {
      await authApi.saveStudentAcademicInformation(token, payload);

      await profile.refresh();

      router.push(returnToReview ? '/student/review' : '/student/english-exam');
    } catch (e) {
      if ((e as ApiError).status === 401) {
        handleUnauthorized();
        return;
      }
      setSaveError(e instanceof Error ? e.message : 'Could not save your academic details. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const renderControl = (level: Qualification, field: FormFieldDef) => {
    const shared = {
      value: valueOf(level, field.key),
      onBlur: () => markLevelFieldTouched(level, field.key),
      onChange: (event: { target: { value: string } }) => setFieldValue(level, field.key, event.target.value)
    };
    const options = rows.optionsFor(field);

    if (field.type === 'select' && !field.allowCustom) {
      return (
        <select {...shared}>
          <option value="" disabled>Select {field.label}</option>
          {options.map(option => <option key={option} value={option}>{option}</option>)}
        </select>
      );
    }
    /** A list the student may add to: a datalist keeps both the suggestions and free text. */
    if (field.type === 'select') {
      const listId = `${level}-${field.key}-list`;
      return (
        <>
          <input type="text" list={listId} placeholder={field.placeholder || 'Select or type your own'} {...shared} />
          <datalist id={listId}>
            {options.map(option => <option key={option} value={option}></option>)}
          </datalist>
        </>
      );
    }
    if (field.type === 'number') {
      return <input type="number" min={field.validation?.min ?? 0} placeholder={field.placeholder || ''} {...shared} />;
    }
    if (field.type === 'textarea') {
      return <textarea rows={3} placeholder={field.placeholder || ''} {...shared} />;
    }
    return <input type="text" placeholder={field.placeholder || ''} {...shared} />;
  };

  return (
    <div className={cx('host')}>
      <section className={cx('step-page')}>
        {!loaded && (
          <div className={cx('profile-form-card')}>
            <p>Loading…</p>
          </div>
        )}

        {loaded && (
          <form className={cx('profile-form-card')} onSubmit={event => { event.preventDefault(); void saveAndContinue(); }}>
            {!!extras.fields.length && (
              <SchemaFields
                fields={extras.fields}
                values={extras.values}
                errors={extras.errors}
                touched={extras.touched}
                cx={cx}
                onChange={extras.setValue}
                onBlur={extras.setTouched}
              />
            )}


            <div className={cx('card-head')}>
              <div className={cx('placeholder-copy')}>
                <div>
                  <h2>{fields.title || 'Academic Information'} details</h2>
                  <p>{fields.description || 'Your information is securely saved to your student profile.'}</p>
                </div>
              </div>
              <span className={cx('step-badge')}>STEP 3 OF 9</span>
            </div>

            <div className={cx('qualification-question')}>
              <h2>Select your appropriate qualification(s) <span className={cx('required-mark')}>*</span></h2>
              <div className={cx('qualification-grid')}>
                {levels.map(level => (
                  <button
                    key={level}
                    type="button"
                    className={cx('qualification-card', isSelected(level) && 'selected')}
                    onClick={() => toggleLevel(level)}
                  >
                    <span className={cx('qual-check')}>✓</span>
                    <strong>{level}</strong>
                  </button>
                ))}
              </div>
              {showSelectionError() && <small className={cx('field-error')}>Select at least one qualification</small>}
            </div>

            <div className={cx('reveal-section', selectedLevels().length > 0 && 'open')}>
              {selectedLevels().map(level => (
                <div key={level} className={cx('level-section')}>
                  <h3 className={cx('section-title')}>{level} details</h3>
                  <div className={cx('dynamic-fields')}>
                    {fieldsFor(level).map(field => (
                      <label
                        key={field.key}
                        className={cx(field.wide && 'wide', showLevelFieldError(level, field.key) && 'field-invalid')}
                      >
                        <span className={cx('field-label')}>
                          {field.label}
                          {field.required && <span className={cx('required-mark')}>*</span>}
                        </span>
                        {renderControl(level, field)}
                        {showLevelFieldError(level, field.key) && (
                          <small className={cx('field-error')}>This field is required</small>
                        )}
                      </label>
                    ))}
                  </div>
                </div>
              ))}

              {!!selectedLevels().length && hasAboveSchoolLevel() && (
                <>
                  <h3 className={cx('section-title')}>{fields.labelOf('educationGap', 'Do you have an education gap?')}</h3>
                  <div className={cx('field-grid')}>
                    <label className={cx('wide')}>
                      <select value={educationGap} onChange={event => setEducationGap(event.target.value)}>
                        <option value="" disabled>Select</option>
                        {educationGapOptions.map(option => <option key={option} value={option}>{option}</option>)}
                      </select>
                    </label>
                  </div>
                </>
              )}
            </div>

            {submitted && (formInvalid || !selectedLevels().length) && (
              <p className={cx('save-message', 'error')}>Please fix the highlighted fields before continuing.</p>
            )}
            {saveError && <p className={cx('save-message', 'error')}>{saveError}</p>}
          </form>
        )}

        <div className={cx('step-actions')}>
          <Link className={cx('button', 'secondary')} href="/student/study-preferences">Previous</Link>
          <button className={cx('button', 'primary')} type="button" disabled={saving || !loaded} onClick={saveAndContinue}>
            {saving ? 'Saving…' : 'Continue'}
          </button>
        </div>
      </section>
    </div>
  );
}
