// src/app/pages/student-portal/financial-information.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, ReactiveFormsModule, ValidationErrors, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { StudentProfileUiStore } from './student-profile-ui.store';
import { AuthApiService } from '../../core/auth-api.service';

function requireOne(control: AbstractControl): ValidationErrors | null {
  return Array.isArray(control.value) && control.value.length ? null : { required: true };
}

const EARNER_INCOME_FIELDS: Record<string, 'fatherIncome' | 'motherIncome' | 'guardianIncome'> = {
  Father: 'fatherIncome',
  Mother: 'motherIncome',
  Guardian: 'guardianIncome'
};

@Component({
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  styleUrl: './financial-information.css',
  template: `
    <section class="step-page">
      <form class="profile-form-card" [formGroup]="form" (ngSubmit)="saveAndContinue()">
        <div class="card-head">
          <div class="placeholder-copy">
            <div>
              <h2>Financial Information details</h2>
              <p>Your information is securely saved to your student profile.</p>
            </div>
          </div>
          <span class="step-badge">STEP 7 OF 9</span>
        </div>

        <h3 class="section-title">Education Funding</h3>
        <div class="field-grid">
          <label class="combo-field wide" [class.field-invalid]="showError('fundingSource')">
            <span class="field-label">How do you plan to fund your education? <span class="required-mark">*</span></span>
            <div class="combo-input-wrap">
              <input #fundingBox type="text" placeholder="Search funding sources"
                [value]="fundingOpen ? (fundingQuery || fundingSource) : fundingSource"
                (focus)="onFundingFocus()" (input)="fundingQuery=$any($event.target).value" (blur)="delayedCloseFunding()">
              <button type="button" class="combo-arrow" [class.open]="fundingOpen" (mousedown)="$event.preventDefault()" (click)="toggleFundingOpen(fundingBox)" aria-label="Toggle funding sources">▾</button>
            </div>
            <ul class="combo-list" *ngIf="fundingOpen" (mousedown)="$event.preventDefault()">
              <li *ngFor="let opt of filteredFunding()" (click)="selectFunding(opt)">
                <span class="option-check" [class.checked]="fundingSource===opt">✓</span>{{opt}}
              </li>
              <li class="combo-empty" *ngIf="!filteredFunding().length">No matching option</li>
            </ul>
            <small class="field-error" *ngIf="showError('fundingSource')">Select how you plan to fund your education</small>
          </label>
        </div>

        <h3 class="section-title">Financial Background</h3>
        <div class="field-grid">
          <label class="combo-field wide" [class.field-invalid]="showError('earningMembers')">
            <span class="field-label">Who is currently earning in your family? <span class="required-mark">*</span></span>
            <div class="combo-input-wrap">
              <input #earningBox type="text" placeholder="Search"
                [value]="earningOpen ? (earningQuery || selectedEarning().join(', ')) : selectedEarning().join(', ')"
                (focus)="onEarningFocus()" (input)="earningQuery=$any($event.target).value" (blur)="delayedCloseEarning()">
              <button type="button" class="combo-arrow" [class.open]="earningOpen" (mousedown)="$event.preventDefault()" (click)="toggleEarningOpen(earningBox)" aria-label="Toggle earning members">▾</button>
            </div>
            <ul class="combo-list" *ngIf="earningOpen" (mousedown)="$event.preventDefault()">
              <li *ngFor="let opt of filteredEarning()" (click)="toggleEarning(opt)">
                <span class="option-check" [class.checked]="isEarningSelected(opt)">✓</span>{{opt}}
              </li>
              <li class="combo-empty" *ngIf="!filteredEarning().length">No matching option</li>
            </ul>
            <small class="field-error" *ngIf="showError('earningMembers')">Select who is currently earning</small>
          </label>

          <label *ngIf="isEarningSelected('Father')" [class.field-invalid]="showError('fatherIncome')">
            <span class="field-label">Father's Annual Income <span class="required-mark">*</span></span>
            <input type="text" formControlName="fatherIncome" placeholder="e.g. 10,00,000" (blur)="markTouched('fatherIncome')">
            <small class="field-error" *ngIf="showError('fatherIncome')">Enter father's annual income</small>
          </label>

          <label *ngIf="isEarningSelected('Mother')" [class.field-invalid]="showError('motherIncome')">
            <span class="field-label">Mother's Annual Income <span class="required-mark">*</span></span>
            <input type="text" formControlName="motherIncome" placeholder="e.g. 8,00,000" (blur)="markTouched('motherIncome')">
            <small class="field-error" *ngIf="showError('motherIncome')">Enter mother's annual income</small>
          </label>

          <label *ngIf="isEarningSelected('Guardian')" [class.field-invalid]="showError('guardianIncome')">
            <span class="field-label">Guardian's Annual Income <span class="required-mark">*</span></span>
            <input type="text" formControlName="guardianIncome" placeholder="e.g. 8,00,000" (blur)="markTouched('guardianIncome')">
            <small class="field-error" *ngIf="showError('guardianIncome')">Enter guardian's annual income</small>
          </label>

          <label [class.field-invalid]="showError('currency')">
            <span class="field-label">Currency <span class="required-mark">*</span></span>
            <select formControlName="currency" (blur)="markTouched('currency')">
              <option value="" disabled>Select currency</option>
              <option *ngFor="let c of currencyOptions" [value]="c">{{c}}</option>
            </select>
            <small class="field-error" *ngIf="showError('currency')">Select a currency</small>
          </label>

          <div class="wide" *ngIf="selectedEarning().length > 1">
            <span class="field-label">Annual Household Income</span>
            <div class="computed-income">{{ householdIncomeTotal() | number }} <ng-container *ngIf="currency">{{currency}}</ng-container></div>
            <small class="field-hint">Auto-calculated as the sum of {{selectedEarning().join(' + ')}} income.</small>
          </div>

          <label class="combo-field wide" [class.field-invalid]="showError('employmentCategory')">
            <span class="field-label">Employment Category <span class="required-mark">*</span></span>
            <div class="combo-input-wrap">
              <input #employmentBox type="text" placeholder="Search employment category"
                [value]="employmentOpen ? (employmentQuery || employmentCategory) : employmentCategory"
                (focus)="onEmploymentFocus()" (input)="employmentQuery=$any($event.target).value" (blur)="delayedCloseEmployment()">
              <button type="button" class="combo-arrow" [class.open]="employmentOpen" (mousedown)="$event.preventDefault()" (click)="toggleEmploymentOpen(employmentBox)" aria-label="Toggle employment category">▾</button>
            </div>
            <ul class="combo-list" *ngIf="employmentOpen" (mousedown)="$event.preventDefault()">
              <li *ngFor="let opt of filteredEmployment()" (click)="selectEmployment(opt)">
                <span class="option-check" [class.checked]="employmentCategory===opt">✓</span>{{opt}}
              </li>
              <li class="combo-empty" *ngIf="!filteredEmployment().length">No matching option</li>
            </ul>
            <small class="field-error" *ngIf="showError('employmentCategory')">Select your employment category</small>
          </label>
        </div>

        <h3 class="section-title">Education Loan</h3>
        <div class="declaration-group">
          <label class="declaration-item">
            <input type="radio" formControlName="needsLoan" value="yes" (blur)="markTouched('needsLoan')">
            <span>Yes, I'll need an education loan to fund part of my studies.</span>
          </label>
          <label class="declaration-item">
            <input type="radio" formControlName="needsLoan" value="no" (blur)="markTouched('needsLoan')">
            <span>No, I'm self-funded or already have funding arranged.</span>
          </label>
          <small class="field-hint" *ngIf="form.value.needsLoan==='yes'">You can check indicative eligibility and upload verification documents anytime from Loan eligibility in your dashboard.</small>
          <small class="field-error" *ngIf="showError('needsLoan')">Let us know if you'll need an education loan</small>
        </div>

        <h3 class="section-title">Declaration</h3>
        <div class="declaration-group">
          <label class="declaration-item">
            <input type="checkbox" formControlName="declarationAccurate">
            <span>I confirm that the financial information provided is accurate.</span>
          </label>
          <label class="declaration-item">
            <input type="checkbox" formControlName="declarationConsent">
            <span>I consent to the verification of my financial information.</span>
          </label>
          <small class="field-error" *ngIf="showError('declarationAccurate') || showError('declarationConsent')">Please accept both declarations to continue</small>
        </div>

        <p class="save-message error" *ngIf="submitted && form.invalid">Please fix the highlighted fields before continuing.</p>
        <p class="save-message error" *ngIf="saveError">{{saveError}}</p>
      </form>

      <div class="step-actions">
        <a class="button secondary" routerLink="/student/work-experience">Previous</a>
        <button class="button primary" type="button" [disabled]="saving" (click)="saveAndContinue()">{{saving ? 'Saving…' : 'Continue'}}</button>
      </div>
    </section>
  `
})
export class FinancialInformationComponent implements OnInit {
  fundingOptions: string[] = [];
  employmentOptions: string[] = [];
  currencyOptions: string[] = [];
  earningOptions: string[] = [];
  fundingQuery = '';
  fundingOpen = false;
  employmentQuery = '';
  employmentOpen = false;
  earningQuery = '';
  earningOpen = false;
  submitted = false;

  form = this.fb.nonNullable.group({
    fundingSource: this.fb.nonNullable.control('', Validators.required),
    earningMembers: this.fb.nonNullable.control<string[]>([], requireOne),
    fatherIncome: this.fb.nonNullable.control(''),
    motherIncome: this.fb.nonNullable.control(''),
    guardianIncome: this.fb.nonNullable.control(''),
    currency: this.fb.nonNullable.control('', Validators.required),
    employmentCategory: this.fb.nonNullable.control('', Validators.required),
    needsLoan: this.fb.nonNullable.control('', Validators.required),
    declarationAccurate: this.fb.nonNullable.control(false, Validators.requiredTrue),
    declarationConsent: this.fb.nonNullable.control(false, Validators.requiredTrue)
  });

  saving = false;
  saveError = '';

  private returnToReview = false;

  constructor(
    private fb: FormBuilder,
    public store: StudentProfileUiStore,
    private router: Router,
    private route: ActivatedRoute,
    private api: AuthApiService,
    private cdr: ChangeDetectorRef
  ) {
    this.returnToReview = this.route.snapshot.queryParamMap.get('from') === 'review';
    this.prefillFromStore();
  }

  private getToken(): string | null {
    return localStorage.getItem('superoffer_access_token') || sessionStorage.getItem('superoffer_access_token');
  }

  private handleUnauthorized() {
    localStorage.removeItem('superoffer_access_token');
    sessionStorage.removeItem('superoffer_access_token');
    this.router.navigate(['/auth/login/student'], { queryParams: { sessionExpired: '1' } });
  }

  /** Local store already hydrated the form synchronously; this only fills in from the
   *  server when the local store had nothing — e.g. a fresh browser/session. */
  async ngOnInit() {
    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }
    try {
      const options = await this.api.getFinancialInformationReferenceData();
      this.fundingOptions = options.fundingSourceOptions;
      this.employmentOptions = options.employmentCategoryOptions;
      this.currencyOptions = options.currencyOptions;
      this.earningOptions = options.earningMemberOptions;
    } catch {
      // Reference data endpoint unreachable — dropdowns stay empty; existing selections still load below.
    }
    if (this.fundingSource) {
      this.cdr.detectChanges();
      return;
    }
    try {
      const profile = await this.api.studentProfile(token);
      const financial = (profile?.financial as Record<string, unknown>) || {};
      if (financial['fundingSource']) {
        this.form.patchValue({
          fundingSource: (financial['fundingSource'] as string) || '',
          currency: (financial['currency'] as string) || '',
          employmentCategory: (financial['employmentCategory'] as string) || '',
          needsLoan: (financial['needsLoan'] as string) || '',
          fatherIncome: (financial['fatherIncome'] as string) || '',
          motherIncome: (financial['motherIncome'] as string) || '',
          guardianIncome: (financial['guardianIncome'] as string) || '',
          declarationAccurate: !!financial['declarationAccurate'],
          declarationConsent: !!financial['declarationConsent']
        });
        const earning = (financial['earningMembers'] as string[]) || [];
        if (earning.length) {
          this.form.get('earningMembers')!.setValue(earning);
          for (const person of earning) {
            const incomeControl = this.form.get(EARNER_INCOME_FIELDS[person]);
            incomeControl?.setValidators(Validators.required);
            incomeControl?.updateValueAndValidity({ emitEvent: false });
          }
        }
      }
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        this.handleUnauthorized();
        return;
      }
      // No saved financial info yet, or the server is unreachable — the student can still fill the form from scratch.
    }
    this.cdr.detectChanges();
  }

  private prefillFromStore() {
    const v = this.store.values;
    this.form.patchValue({
      fundingSource: v['fundingSource'] || '',
      currency: v['currency'] || '',
      employmentCategory: v['employmentCategory'] || '',
      needsLoan: v['needsLoan'] || '',
      fatherIncome: v['fatherIncome'] || '',
      motherIncome: v['motherIncome'] || '',
      guardianIncome: v['guardianIncome'] || '',
      declarationAccurate: v['declarationAccurate'] === 'true',
      declarationConsent: v['declarationConsent'] === 'true'
    });
    const earning = (v['earningMembers'] || '').split(',').map(s => s.trim()).filter(Boolean);
    if (!earning.length) return;
    this.form.get('earningMembers')!.setValue(earning);
    for (const person of earning) {
      const incomeControl = this.form.get(EARNER_INCOME_FIELDS[person]);
      incomeControl?.setValidators(Validators.required);
      incomeControl?.updateValueAndValidity({ emitEvent: false });
    }
  }

  get fundingSource(): string { return this.form.get('fundingSource')!.value; }
  get currency(): string { return this.form.get('currency')!.value; }
  filteredFunding(): string[] {
    const q = this.fundingQuery.trim().toLowerCase();
    return !q ? this.fundingOptions : this.fundingOptions.filter(opt => opt.toLowerCase().includes(q));
  }
  onFundingFocus() { this.fundingOpen = true; this.fundingQuery = ''; }
  delayedCloseFunding() { this.fundingOpen = false; }
  toggleFundingOpen(inputEl: HTMLInputElement) {
    if (this.fundingOpen) { this.delayedCloseFunding(); inputEl.blur(); }
    else { this.onFundingFocus(); inputEl.focus(); }
  }
  selectFunding(value: string) {
    const control = this.form.get('fundingSource')!;
    control.setValue(this.fundingSource === value ? '' : value);
    control.markAsTouched();
    this.fundingQuery = '';
    this.delayedCloseFunding();
  }

  get employmentCategory(): string { return this.form.get('employmentCategory')!.value; }
  filteredEmployment(): string[] {
    const q = this.employmentQuery.trim().toLowerCase();
    return !q ? this.employmentOptions : this.employmentOptions.filter(opt => opt.toLowerCase().includes(q));
  }
  onEmploymentFocus() { this.employmentOpen = true; this.employmentQuery = ''; }
  delayedCloseEmployment() { this.employmentOpen = false; }
  toggleEmploymentOpen(inputEl: HTMLInputElement) {
    if (this.employmentOpen) { this.delayedCloseEmployment(); inputEl.blur(); }
    else { this.onEmploymentFocus(); inputEl.focus(); }
  }
  selectEmployment(value: string) {
    const control = this.form.get('employmentCategory')!;
    control.setValue(this.employmentCategory === value ? '' : value);
    control.markAsTouched();
    this.employmentQuery = '';
    this.delayedCloseEmployment();
  }
  selectedEarning(): string[] { return this.form.get('earningMembers')!.value as string[]; }
  isEarningSelected(value: string): boolean { return this.selectedEarning().includes(value); }
  filteredEarning(): string[] {
    const q = this.earningQuery.trim().toLowerCase();
    return !q ? this.earningOptions : this.earningOptions.filter(opt => opt.toLowerCase().includes(q));
  }
  onEarningFocus() { this.earningOpen = true; this.earningQuery = ''; }
  delayedCloseEarning() { this.earningOpen = false; }
  toggleEarningOpen(inputEl: HTMLInputElement) {
    if (this.earningOpen) { this.delayedCloseEarning(); inputEl.blur(); }
    else { this.onEarningFocus(); inputEl.focus(); }
  }
  toggleEarning(value: string) {
    const control = this.form.get('earningMembers')!;
    const current: string[] = control.value || [];
    const next = current.includes(value) ? current.filter(item => item !== value) : [...current, value];
    control.setValue(next);
    control.markAsTouched();
    this.earningQuery = '';

    const incomeKey = EARNER_INCOME_FIELDS[value];
    const incomeControl = this.form.get(incomeKey)!;
    if (next.includes(value)) {
      incomeControl.setValidators(Validators.required);
    } else {
      incomeControl.setValidators(null);
      incomeControl.setValue('');
      incomeControl.markAsUntouched();
    }
    incomeControl.updateValueAndValidity({ emitEvent: false });
  }
  private parseAmount(value: string): number {
    return Number((value || '').replace(/[^0-9.]/g, '')) || 0;
  }
  householdIncomeTotal(): number {
    return this.selectedEarning().reduce((sum, earner) => sum + this.parseAmount(this.form.get(EARNER_INCOME_FIELDS[earner])!.value), 0);
  }

  markTouched(key: string) { this.form.get(key)!.markAsTouched(); }
  showError(key: string): boolean {
    const control = this.form.get(key)!;
    return (control.touched || this.submitted) && control.invalid;
  }

  async saveAndContinue() {
    this.submitted = true;
    this.saveError = '';
    this.form.markAllAsTouched();
    if (this.form.invalid) return;

    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }

    const value = this.form.getRawValue();
    const annualHouseholdIncome = String(this.householdIncomeTotal());

    this.saving = true;
    try {
      await this.api.saveStudentFinancialInformation(token, {
        fundingSource: value.fundingSource,
        earningMembers: value.earningMembers,
        fatherIncome: value.fatherIncome || undefined,
        motherIncome: value.motherIncome || undefined,
        guardianIncome: value.guardianIncome || undefined,
        annualHouseholdIncome,
        currency: value.currency,
        employmentCategory: value.employmentCategory,
        needsLoan: value.needsLoan,
        declarationAccurate: value.declarationAccurate,
        declarationConsent: value.declarationConsent
      });

      this.store.values['fundingSource'] = value.fundingSource;
      this.store.values['earningMembers'] = value.earningMembers.join(', ');
      this.store.values['fatherIncome'] = value.fatherIncome;
      this.store.values['motherIncome'] = value.motherIncome;
      this.store.values['guardianIncome'] = value.guardianIncome;
      this.store.values['annualHouseholdIncome'] = annualHouseholdIncome;
      this.store.values['currency'] = value.currency;
      this.store.values['employmentCategory'] = value.employmentCategory;
      this.store.values['needsLoan'] = value.needsLoan;
      this.store.values['declarationAccurate'] = String(value.declarationAccurate);
      this.store.values['declarationConsent'] = String(value.declarationConsent);

      this.router.navigateByUrl(this.returnToReview ? '/student/review' : '/student/projects');
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        this.handleUnauthorized();
        return;
      }
      this.saveError = e instanceof Error ? e.message : 'Could not save your financial details. Please try again.';
    } finally {
      this.saving = false;
      this.cdr.detectChanges();
    }
  }
}

// components/student/FinancialInformation.tsx
'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { authApi, type ApiError } from '@/lib/api/auth-api';
import { useSectionFields } from '@/lib/forms/use-section-fields';
import { classNames } from '@/lib/cx';
import { clearAccessToken, readAccessToken } from '@/lib/storage';
import { useSchemaExtras } from '@/lib/forms/use-schema-extras';
import { useStudentProfile } from '@/lib/stores/student-profile.store';
import styles from '@/styles/FinancialInformation.module.css';
import { SchemaFields } from './SchemaFields';

const cx = classNames(styles);

type IncomeField = 'fatherIncome' | 'motherIncome' | 'guardianIncome';

const EARNER_INCOME_FIELDS: Record<string, IncomeField> = {
  Father: 'fatherIncome',
  Mother: 'motherIncome',
  Guardian: 'guardianIncome'
};

const INCOME_LABELS: Record<IncomeField, { label: string; placeholder: string; error: string }> = {
  fatherIncome: { label: "Father's Annual Income", placeholder: 'e.g. 10,00,000', error: "Enter father's annual income" },
  motherIncome: { label: "Mother's Annual Income", placeholder: 'e.g. 8,00,000', error: "Enter mother's annual income" },
  guardianIncome: { label: "Guardian's Annual Income", placeholder: 'e.g. 8,00,000', error: "Enter guardian's annual income" }
};

const parseAmount = (value: string) => Number((value || '').replace(/[^0-9.]/g, '')) || 0;

/** Single-select combo box shared by the funding-source and employment-category fields. */
function SingleComboField({
  label, placeholder, toggleLabel, emptyText, options, selected, open, query, invalid, error,
  onOpen, onClose, onQueryChange, onSelect
}: {
  label: string;
  placeholder: string;
  toggleLabel: string;
  emptyText: string;
  options: string[];
  selected: string;
  open: boolean;
  query: string;
  invalid: boolean;
  error: string;
  onOpen(): void;
  onClose(): void;
  onQueryChange(value: string): void;
  onSelect(value: string): void;
}) {
  const input = useRef<HTMLInputElement>(null);

  return (
    <label className={cx('combo-field', 'wide', invalid && 'field-invalid')}>
      <span className={cx('field-label')}>{label} <span className={cx('required-mark')}>*</span></span>
      <div className={cx('combo-input-wrap')}>
        <input
          ref={input}
          type="text"
          placeholder={placeholder}
          value={open ? query || selected : selected}
          onFocus={onOpen}
          onChange={event => onQueryChange(event.target.value)}
          onBlur={onClose}
        />
        <button
          type="button"
          className={cx('combo-arrow', open && 'open')}
          onMouseDown={event => event.preventDefault()}
          onClick={() => {
            if (open) {
              onClose();
              input.current?.blur();
            } else {
              onOpen();
              input.current?.focus();
            }
          }}
          aria-label={toggleLabel}
        >
          ▾
        </button>
      </div>
      {open && (
        <ul className={cx('combo-list')} onMouseDown={event => event.preventDefault()}>
          {options.map(option => (
            <li key={option} onClick={() => onSelect(option)}>
              <span className={cx('option-check', selected === option && 'checked')}>✓</span>{option}
            </li>
          ))}
          {!options.length && <li className={cx('combo-empty')}>{emptyText}</li>}
        </ul>
      )}
      {invalid && <small className={cx('field-error')}>{error}</small>}
    </label>
  );
}

export function FinancialInformation() {
  const profile = useStudentProfile();
  const router = useRouter();
  const searchParams = useSearchParams();
  const returnToReview = searchParams.get('from') === 'review';

  const [fundingOptions, setFundingOptions] = useState<string[]>([]);
  const [employmentOptions, setEmploymentOptions] = useState<string[]>([]);
  const [currencyOptions, setCurrencyOptions] = useState<string[]>([]);
  const [earningOptions, setEarningOptions] = useState<string[]>([]);

  const [fundingSource, setFundingSource] = useState('');
  const [earningMembers, setEarningMembers] = useState<string[]>([]);
  const [incomes, setIncomes] = useState<Record<IncomeField, string>>({ fatherIncome: '', motherIncome: '', guardianIncome: '' });
  const [currency, setCurrency] = useState('');
  const [employmentCategory, setEmploymentCategory] = useState('');
  const [needsLoan, setNeedsLoan] = useState('');
  const [declarationAccurate, setDeclarationAccurate] = useState(false);
  const [declarationConsent, setDeclarationConsent] = useState(false);

  const [openField, setOpenField] = useState<'funding' | 'employment' | 'earning' | null>(null);
  const [queries, setQueries] = useState({ funding: '', employment: '', earning: '' });
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [submitted, setSubmitted] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');
  const seeded = useRef(false);

  /** Fields this step draws by hand; anything else the schema declares is added below. */
  const FIN_CODED = ['fundingSource', 'earningMembers', 'earnerIncomes', 'fatherIncome', 'motherIncome', 'guardianIncome', 'annualHouseholdIncome', 'currency', 'employmentCategory', 'needsLoan', 'declarationAccurate', 'declarationConsent'];

  /** What the published form says about the fields drawn by hand below. */
  const fields = useSectionFields('financialInformation', FIN_CODED);

  const extras = useSchemaExtras(
    'financialInformation',
    FIN_CODED,
    profile.profile.financial,
    profile.loaded
  );


  const earningInput = useRef<HTMLInputElement>(null);

  const handleUnauthorized = () => {
    clearAccessToken();
    router.push('/auth/login/student?sessionExpired=1');
  };

  /** Seed once from the section the server already holds. */
  useEffect(() => {
    if (seeded.current || !profile.loaded) return;
    seeded.current = true;
    const saved = profile.profile.financial || {};
    if (!saved['fundingSource']) return;
    setFundingSource(String(saved['fundingSource'] || ''));
    setCurrency(String(saved['currency'] || ''));
    setEmploymentCategory(String(saved['employmentCategory'] || ''));
    setNeedsLoan(String(saved['needsLoan'] || ''));
    setIncomes({
      fatherIncome: String(saved['fatherIncome'] || ''),
      motherIncome: String(saved['motherIncome'] || ''),
      guardianIncome: String(saved['guardianIncome'] || '')
    });
    setDeclarationAccurate(Boolean(saved['declarationAccurate']));
    setDeclarationConsent(Boolean(saved['declarationConsent']));
    setEarningMembers((saved['earningMembers'] as string[]) || []);
  }, [profile.loaded, profile.profile.financial]);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      const token = readAccessToken();
      if (!token) {
        router.push('/auth/login/student');
        return;
      }
      try {
        const options = await authApi.getFinancialInformationReferenceData();
        if (cancelled) return;
        setFundingOptions(options.fundingSourceOptions);
        setEmploymentOptions(options.employmentCategoryOptions);
        setCurrencyOptions(options.currencyOptions);
        setEarningOptions(options.earningMemberOptions);
      } catch {
        // Reference data endpoint unreachable — dropdowns stay empty.
      }
    })();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const filtered = (options: string[], query: string) => {
    const q = query.trim().toLowerCase();
    return !q ? options : options.filter(option => option.toLowerCase().includes(q));
  };

  const isEarningSelected = (value: string) => earningMembers.includes(value);

  const toggleEarning = (value: string) => {
    setEarningMembers(current => {
      const next = current.includes(value) ? current.filter(item => item !== value) : [...current, value];
      /** An earner that is deselected loses its income; one that is selected requires it. */
      const field = EARNER_INCOME_FIELDS[value];
      if (field && !next.includes(value)) setIncomes(prev => ({ ...prev, [field]: '' }));
      return next;
    });
    setTouched(current => ({ ...current, earningMembers: true }));
    setQueries(current => ({ ...current, earning: '' }));
  };

  const householdIncomeTotal = () =>
    earningMembers.reduce((sum, earner) => {
      const field = EARNER_INCOME_FIELDS[earner];
      return sum + (field ? parseAmount(incomes[field]) : 0);
    }, 0);

  const markTouched = (key: string) => setTouched(current => ({ ...current, [key]: true }));

  /**
   * Only what the published form still asks for is enforced. A field the admin
   * has hidden or made optional cannot hold a student on this step.
   *
   * The per-earner incomes hang off `earnerIncomes`, since that is the block the
   * builder shows them under.
   */
  const stillAsks = (key: string, under = key) =>
    fields.shows(under) && fields.isRequired(key === under ? key : under, true);

  const invalidFields: Record<string, boolean> = {
    fundingSource: stillAsks('fundingSource') && !fundingSource,
    earningMembers: stillAsks('earningMembers') && !earningMembers.length,
    currency: stillAsks('currency') && !currency,
    employmentCategory: stillAsks('employmentCategory') && !employmentCategory,
    needsLoan: stillAsks('needsLoan') && !needsLoan,
    declarationAccurate: stillAsks('declarationAccurate') && !declarationAccurate,
    declarationConsent: stillAsks('declarationConsent') && !declarationConsent,
    fatherIncome: fields.shows('earnerIncomes') && isEarningSelected('Father') && !incomes.fatherIncome.trim(),
    motherIncome: fields.shows('earnerIncomes') && isEarningSelected('Mother') && !incomes.motherIncome.trim(),
    guardianIncome: fields.shows('earnerIncomes') && isEarningSelected('Guardian') && !incomes.guardianIncome.trim()
  };

  const showError = (key: string) => (touched[key] || submitted) && invalidFields[key];
  const formInvalid = Object.values(invalidFields).some(Boolean);

  const saveAndContinue = async () => {
    setSubmitted(true);
    extras.touchAll();
    setSaveError('');
    if (formInvalid) return;

    const token = readAccessToken();
    if (!token) {
      router.push('/auth/login/student');
      return;
    }

    const annualHouseholdIncome = String(householdIncomeTotal());

    setSaving(true);
    try {
      await authApi.saveStudentFinancialInformation(token, {
        ...extras.values0,
        fundingSource,
        earningMembers,
        fatherIncome: incomes.fatherIncome || undefined,
        motherIncome: incomes.motherIncome || undefined,
        guardianIncome: incomes.guardianIncome || undefined,
        annualHouseholdIncome,
        currency,
        employmentCategory,
        needsLoan,
        declarationAccurate,
        declarationConsent
      });

      await profile.refresh();

      router.push(returnToReview ? '/student/review' : '/student/projects');
    } catch (e) {
      if ((e as ApiError).status === 401) {
        handleUnauthorized();
        return;
      }
      setSaveError(e instanceof Error ? e.message : 'Could not save your financial details. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const incomeField = (earner: string) => {
    const field = EARNER_INCOME_FIELDS[earner];
    if (!field || !isEarningSelected(earner)) return null;
    const copy = INCOME_LABELS[field];
    return (
      <label key={field} className={cx(showError(field) && 'field-invalid')}>
        <span className={cx('field-label')}>{copy.label} <span className={cx('required-mark')}>*</span></span>
        <input
          type="text"
          placeholder={copy.placeholder}
          value={incomes[field]}
          onChange={event => setIncomes(current => ({ ...current, [field]: event.target.value }))}
          onBlur={() => markTouched(field)}
        />
        {showError(field) && <small className={cx('field-error')}>{copy.error}</small>}
      </label>
    );
  };

  return (
    <div className={cx('host')}>
      <section className={cx('step-page')}>
        <form className={cx('profile-form-card')} onSubmit={event => { event.preventDefault(); void saveAndContinue(); }}>
          <div className={cx('card-head')}>
            <div className={cx('placeholder-copy')}>
              <div>
                <h2>{fields.title || 'Financial Information'} details</h2>
                <p>{fields.description || 'Your information is securely saved to your student profile.'}</p>
              </div>
            </div>
            <span className={cx('step-badge')}>STEP 7 OF 9</span>
          </div>

          <h3 className={cx('section-title')}>{fields.groupLabel('funding', 'Education Funding')}</h3>
          <div className={cx('field-grid')}>
            {!!extras.fields.length && (
              <SchemaFields
                fields={extras.fields}
                values={extras.values}
                errors={extras.errors}
                touched={extras.touched}
                cx={cx}
                onChange={extras.setValue}
                onBlur={extras.setTouched}
              />
            )}


            <SingleComboField
              label={fields.labelOf('fundingSource', 'How do you plan to fund your education?')}
              placeholder="Search funding sources"
              toggleLabel="Toggle funding sources"
              emptyText="No matching option"
              options={filtered(fundingOptions, queries.funding)}
              selected={fundingSource}
              open={openField === 'funding'}
              query={queries.funding}
              invalid={!!showError('fundingSource')}
              error="Select how you plan to fund your education"
              onOpen={() => { setOpenField('funding'); setQueries(c => ({ ...c, funding: '' })); }}
              onClose={() => setOpenField(current => (current === 'funding' ? null : current))}
              onQueryChange={value => setQueries(c => ({ ...c, funding: value }))}
              onSelect={value => {
                setFundingSource(current => (current === value ? '' : value));
                markTouched('fundingSource');
                setQueries(c => ({ ...c, funding: '' }));
                setOpenField(null);
              }}
            />
          </div>

          <h3 className={cx('section-title')}>{fields.groupLabel('background', 'Financial Background')}</h3>
          <div className={cx('field-grid')}>
            <label className={cx('combo-field', 'wide', showError('earningMembers') && 'field-invalid')}>
              <span className={cx('field-label')}>{fields.labelOf('earningMembers', 'Who is currently earning in your family?')}{fields.isRequired('earningMembers', true) && <span className={cx('required-mark')}> *</span>}</span>
              <div className={cx('combo-input-wrap')}>
                <input
                  ref={earningInput}
                  type="text"
                  placeholder="Search"
                  value={openField === 'earning' ? queries.earning || earningMembers.join(', ') : earningMembers.join(', ')}
                  onFocus={() => { setOpenField('earning'); setQueries(c => ({ ...c, earning: '' })); }}
                  onChange={event => setQueries(c => ({ ...c, earning: event.target.value }))}
                  onBlur={() => setOpenField(current => (current === 'earning' ? null : current))}
                />
                <button
                  type="button"
                  className={cx('combo-arrow', openField === 'earning' && 'open')}
                  onMouseDown={event => event.preventDefault()}
                  onClick={() => {
                    if (openField === 'earning') {
                      setOpenField(null);
                      earningInput.current?.blur();
                    } else {
                      setOpenField('earning');
                      setQueries(c => ({ ...c, earning: '' }));
                      earningInput.current?.focus();
                    }
                  }}
                  aria-label="Toggle earning members"
                >
                  ▾
                </button>
              </div>
              {openField === 'earning' && (
                <ul className={cx('combo-list')} onMouseDown={event => event.preventDefault()}>
                  {filtered(earningOptions, queries.earning).map(option => (
                    <li key={option} onClick={() => toggleEarning(option)}>
                      <span className={cx('option-check', isEarningSelected(option) && 'checked')}>✓</span>{option}
                    </li>
                  ))}
                  {!filtered(earningOptions, queries.earning).length && (
                    <li className={cx('combo-empty')}>No matching option</li>
                  )}
                </ul>
              )}
              {showError('earningMembers') && <small className={cx('field-error')}>Select who is currently earning</small>}
            </label>

            {['Father', 'Mother', 'Guardian'].map(incomeField)}

            {fields.shows('currency') && (
              <label className={cx(showError('currency') && 'field-invalid')}>
                <span className={cx('field-label')}>{fields.labelOf('currency', 'Currency')}{fields.isRequired('currency', true) && <span className={cx('required-mark')}> *</span>}</span>
                <select
                  value={currency}
                  onChange={event => { setCurrency(event.target.value); markTouched('currency'); }}
                  onBlur={() => markTouched('currency')}
                >
                  <option value="" disabled>Select currency</option>
                  {currencyOptions.map(option => <option key={option} value={option}>{option}</option>)}
                </select>
                {showError('currency') && <small className={cx('field-error')}>Select a currency</small>}
              </label>
            )}

            {earningMembers.length > 1 && (
              <div className={cx('wide')}>
                <span className={cx('field-label')}>{fields.labelOf('annualHouseholdIncome', 'Annual Household Income')}</span>
                <div className={cx('computed-income')}>
                  {householdIncomeTotal().toLocaleString('en-US')} {currency}
                </div>
                <small className={cx('field-hint')}>
                  Auto-calculated as the sum of {earningMembers.join(' + ')} income.
                </small>
              </div>
            )}

            <SingleComboField
              label={fields.labelOf('employmentCategory', 'Employment Category')}
              placeholder="Search employment category"
              toggleLabel="Toggle employment category"
              emptyText="No matching option"
              options={filtered(employmentOptions, queries.employment)}
              selected={employmentCategory}
              open={openField === 'employment'}
              query={queries.employment}
              invalid={!!showError('employmentCategory')}
              error="Select your employment category"
              onOpen={() => { setOpenField('employment'); setQueries(c => ({ ...c, employment: '' })); }}
              onClose={() => setOpenField(current => (current === 'employment' ? null : current))}
              onQueryChange={value => setQueries(c => ({ ...c, employment: value }))}
              onSelect={value => {
                setEmploymentCategory(current => (current === value ? '' : value));
                markTouched('employmentCategory');
                setQueries(c => ({ ...c, employment: '' }));
                setOpenField(null);
              }}
            />
          </div>

          <h3 className={cx('section-title')}>{fields.groupLabel('loan', 'Education Loan')}</h3>
          <div className={cx('declaration-group')}>
            <label className={cx('declaration-item')}>
              <input
                type="radio" name="needsLoan" value="yes"
                checked={needsLoan === 'yes'}
                onChange={() => { setNeedsLoan('yes'); markTouched('needsLoan'); }}
              />
              <span>Yes, I&apos;ll need an education loan to fund part of my studies.</span>
            </label>
            <label className={cx('declaration-item')}>
              <input
                type="radio" name="needsLoan" value="no"
                checked={needsLoan === 'no'}
                onChange={() => { setNeedsLoan('no'); markTouched('needsLoan'); }}
              />
              <span>No, I&apos;m self-funded or already have funding arranged.</span>
            </label>
            {needsLoan === 'yes' && (
              <small className={cx('field-hint')}>
                You can check indicative eligibility and upload verification documents anytime from Loan eligibility in your dashboard.
              </small>
            )}
            {showError('needsLoan') && <small className={cx('field-error')}>Let us know if you&apos;ll need an education loan</small>}
          </div>

          <h3 className={cx('section-title')}>{fields.groupLabel('declaration', 'Declaration')}</h3>
          <div className={cx('declaration-group')}>
            <label className={cx('declaration-item')}>
              <input
                type="checkbox"
                checked={declarationAccurate}
                onChange={event => setDeclarationAccurate(event.target.checked)}
              />
              <span>I confirm that the financial information provided is accurate.</span>
            </label>
            <label className={cx('declaration-item')}>
              <input
                type="checkbox"
                checked={declarationConsent}
                onChange={event => setDeclarationConsent(event.target.checked)}
              />
              <span>I consent to the verification of my financial information.</span>
            </label>
            {(showError('declarationAccurate') || showError('declarationConsent')) && (
              <small className={cx('field-error')}>Please accept both declarations to continue</small>
            )}
          </div>

          {submitted && formInvalid && (
            <p className={cx('save-message', 'error')}>Please fix the highlighted fields before continuing.</p>
          )}
          {saveError && <p className={cx('save-message', 'error')}>{saveError}</p>}
        </form>

        <div className={cx('step-actions')}>
          <Link className={cx('button', 'secondary')} href="/student/work-experience">Previous</Link>
          <button className={cx('button', 'primary')} type="button" disabled={saving} onClick={saveAndContinue}>
            {saving ? 'Saving…' : 'Continue'}
          </button>
        </div>
      </section>
    </div>
  );
}
