// src/app/pages/student-portal/personal-information.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { StudentProfileUiStore } from './student-profile-ui.store';
import { CountryInfo } from './geo-data';
import { AuthApiService } from '../../core/auth-api.service';

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule],
  styleUrl: './personal-information.css',
  template: `
    <section class="step-page">
      <div class="profile-form-card">
        <div class="card-head">
          <div class="placeholder-copy">
            <div>
              <h2>Personal Information details</h2>
              <p>Your information is securely saved to your student profile.</p>
            </div>
          </div>
          <span class="step-badge">STEP 1 OF 9</span>
        </div>

        <div class="field-grid">
          <label [class.field-invalid]="showError('fullName')">
            <span class="field-label">Full Name <span class="required-mark">*</span></span>
            <input type="text" name="fullName" autocomplete="name" placeholder="Aarav Mehta"
              [(ngModel)]="store.values['fullName']" (blur)="markTouched('fullName')">
            <small class="field-error" *ngIf="showError('fullName')">{{fullNameError}}</small>
          </label>

          <label [class.field-invalid]="showError('email')">
            <span class="field-label">Email Address <span class="required-mark">*</span></span>
            <input type="email" name="email" autocomplete="email" placeholder="aarav@example.com"
              [(ngModel)]="store.values['email']" (blur)="markTouched('email')">
            <small class="field-error" *ngIf="showError('email')">{{emailError}}</small>
          </label>

          <div class="field-pair-row">
            <label [class.field-invalid]="showError('mobile')">
              <span class="field-label">Mobile Number <span class="required-mark">*</span></span>
              <div class="phone-group">
                <select class="dial-select" name="mobileCountry" [(ngModel)]="store.values['mobileCountry']" (blur)="markTouched('mobile')" (change)="markTouched('mobile')">
                  <option value="" disabled>+</option>
                  <option *ngFor="let c of countries" [value]="c.iso2" [title]="c.name">{{c.dial}}</option>
                </select>
                <input type="tel" name="mobileNumber" autocomplete="tel-national" placeholder="98765 43210"
                  [(ngModel)]="store.values['mobileNumber']" (blur)="markTouched('mobile')">
              </div>
              <small class="field-error" *ngIf="showError('mobile')">{{mobileError}}</small>
              <small class="field-hint" *ngIf="!showError('mobile')">&nbsp;</small>
            </label>

            <label [class.field-invalid]="showError('altMobile')">
              <span class="field-label">Additional Mobile Number</span>
              <div class="phone-group">
                <select class="dial-select" name="altMobileCountry" [(ngModel)]="store.values['altMobileCountry']" (blur)="markTouched('altMobile')" (change)="markTouched('altMobile')">
                  <option value="" disabled>+</option>
                  <option *ngFor="let c of countries" [value]="c.iso2" [title]="c.name">{{c.dial}}</option>
                </select>
                <input type="tel" name="altMobileNumber" autocomplete="tel-national" placeholder="Optional"
                  [(ngModel)]="store.values['altMobileNumber']" (blur)="markTouched('altMobile')">
              </div>
              <small class="field-error" *ngIf="showError('altMobile')">{{altMobileError}}</small>
              <small class="field-hint" *ngIf="!showError('altMobile')">&nbsp;</small>
            </label>
          </div>

          <div class="field-pair-row">
            <label class="combo-field" [class.field-invalid]="showError('country')">
              <span class="field-label">Country <span class="required-mark">*</span></span>
              <input type="text" name="country" autocomplete="country-name" placeholder="Search for your country"
                [(ngModel)]="store.values['country']"
                (focus)="countryOpen=true" (input)="onCountryInput()" (blur)="onCountryBlur()">
              <ul class="combo-list" *ngIf="countryOpen">
                <li *ngFor="let c of filteredCountries" (mousedown)="selectCountry(c)">{{c.name}}</li>
                <li class="combo-empty" *ngIf="!filteredCountries.length">No matching country</li>
              </ul>
              <small class="field-error" *ngIf="showError('country')">{{countryError}}</small>
            </label>

            <label [class.field-invalid]="showError('city')">
              <span class="field-label">Current City <span class="required-mark">*</span></span>
              <select *ngIf="hasCityOptions" name="city" [(ngModel)]="store.values['city']" (blur)="markTouched('city')" (change)="markTouched('city')">
                <option value="" disabled>Select city</option>
                <option *ngFor="let city of cityOptions" [value]="city">{{city}}</option>
              </select>
              <input *ngIf="!hasCityOptions" type="text" name="city" placeholder="Enter your current city"
                [(ngModel)]="store.values['city']" [disabled]="!countryValid" (blur)="markTouched('city')">
              <small class="field-hint" *ngIf="!countryValid">Select a valid country first</small>
              <small class="field-hint" *ngIf="countryValid && !hasCityOptions">City list not available for this country — type your city</small>
              <small class="field-error" *ngIf="showError('city')">{{cityError}}</small>
            </label>
          </div>
        </div>

        <p class="save-message error" *ngIf="submitted && !isValid">Please fix the highlighted fields before continuing.</p>
        <p class="save-message error" *ngIf="saveError">{{saveError}}</p>
      </div>

      <div class="step-actions">
        <span></span>
        <button class="button primary" type="button" [disabled]="saving" (click)="saveAndContinue()">{{saving ? 'Saving…' : 'Continue'}}</button>
      </div>
    </section>
  `
})
export class PersonalInformationComponent implements OnInit {
  countries: CountryInfo[] = [];
  countryCityOptions: Record<string, string[]> = {};
  countryOpen = false;
  touched: Record<string, boolean> = {};
  submitted = false;
  saving = false;
  saveError = '';

  private returnToReview = false;

  constructor(
    public store: StudentProfileUiStore,
    private router: Router,
    private route: ActivatedRoute,
    private api: AuthApiService,
    private cdr: ChangeDetectorRef
  ) {
    if (!this.store.values['mobileCountry']) this.store.values['mobileCountry'] = 'IN';
    if (!this.store.values['altMobileCountry']) this.store.values['altMobileCountry'] = 'IN';
    this.returnToReview = this.route.snapshot.queryParamMap.get('from') === 'review';
  }

  private getToken(): string | null {
    return localStorage.getItem('superoffer_access_token') || sessionStorage.getItem('superoffer_access_token');
  }

  async ngOnInit() {
    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }
    try {
      const geo = await this.api.getGeoReferenceData();
      this.countries = geo.countries;
      this.countryCityOptions = { India: geo.indiaCities };
    } catch {
      // Reference data endpoint unreachable — dropdowns stay empty; the student can still type a country/city.
    }
    try {
      const profile = await this.api.studentProfile(token);
      const personal = (profile?.personal as Record<string, string>) || {};
      for (const key of Object.keys(personal)) {
        if (!this.store.values[key]) this.store.values[key] = personal[key];
      }
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        localStorage.removeItem('superoffer_access_token');
        sessionStorage.removeItem('superoffer_access_token');
        this.router.navigate(['/auth/login/student'], { queryParams: { sessionExpired: '1' } });
        return;
      }
      // No saved profile yet, or the server is unreachable — the student can still fill the form from scratch.
    }
    this.cdr.detectChanges();
  }

  markTouched(key: string) { this.touched[key] = true; }
  showError(key: string): boolean {
    return (this.touched[key] || this.submitted) && !!this.errorFor(key);
  }
  private errorFor(key: string): string {
    switch (key) {
      case 'fullName': return this.fullNameError;
      case 'email': return this.emailError;
      case 'mobile': return this.mobileError;
      case 'altMobile': return this.altMobileError;
      case 'country': return this.countryError;
      case 'city': return this.cityError;
      default: return '';
    }
  }

  get fullNameError(): string {
    return (this.store.values['fullName'] || '').trim().length >= 2 ? '' : 'Enter your full name';
  }

  get emailError(): string {
    const value = (this.store.values['email'] || '').trim();
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value) ? '' : 'Enter a valid email address';
  }

  get mobileError(): string {
    if (!this.store.values['mobileCountry']) return 'Select a country code';
    const digits = (this.store.values['mobileNumber'] || '').replace(/\D/g, '');
    return /^\d{6,14}$/.test(digits) ? '' : 'Enter a valid mobile number';
  }

  get altMobileError(): string {
    const raw = (this.store.values['altMobileNumber'] || '').trim();
    if (!raw) return '';
    if (!this.store.values['altMobileCountry']) return 'Select a country code';
    const digits = raw.replace(/\D/g, '');
    return /^\d{6,14}$/.test(digits) ? '' : 'Enter a valid mobile number';
  }

  get countryValid(): boolean {
    return this.countries.some(c => c.name === (this.store.values['country'] || ''));
  }
  get countryError(): string { return this.countryValid ? '' : 'Select a valid country from the list'; }

  get cityOptions(): string[] { return this.countryCityOptions[this.store.values['country'] || ''] || []; }
  get hasCityOptions(): boolean { return this.cityOptions.length > 0; }
  get cityError(): string { return (this.store.values['city'] || '').trim() ? '' : 'Select or enter your current city'; }

  get filteredCountries(): CountryInfo[] {
    const query = (this.store.values['country'] || '').trim().toLowerCase();
    return !query ? this.countries : this.countries.filter(c => c.name.toLowerCase().includes(query));
  }

  onCountryInput() { this.countryOpen = true; }
  onCountryBlur() { setTimeout(() => this.countryOpen = false, 150); }
  selectCountry(country: CountryInfo) {
    const changed = this.store.values['country'] !== country.name;
    this.store.values['country'] = country.name;
    this.countryOpen = false;
    if (changed) this.store.values['city'] = '';
  }

  get isValid(): boolean {
    return !this.fullNameError && !this.emailError && !this.mobileError && !this.altMobileError && !this.countryError && !this.cityError;
  }

  private dialFor(iso2: string): string { return this.countries.find(c => c.iso2 === iso2)?.dial || ''; }

  async saveAndContinue() {
    this.submitted = true;
    this.saveError = '';
    if (!this.isValid) return;

    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }

    const mobile = `${this.dialFor(this.store.values['mobileCountry'])} ${this.store.values['mobileNumber'] || ''}`.trim();
    this.store.values['phone'] = mobile;
    this.store.values['location'] = [this.store.values['city'], this.store.values['country']].filter(Boolean).join(', ');

    const payload = {
      fullName: this.store.values['fullName'],
      email: this.store.values['email'],
      mobileCountry: this.store.values['mobileCountry'],
      mobileNumber: this.store.values['mobileNumber'],
      altMobileCountry: this.store.values['altMobileCountry'] || undefined,
      altMobileNumber: this.store.values['altMobileNumber'] || undefined,
      country: this.store.values['country'],
      city: this.store.values['city'],
      phone: this.store.values['phone'],
      location: this.store.values['location']
    };

    this.saving = true;
    try {
      await this.api.saveStudentPersonalInformation(token, payload);
      this.router.navigateByUrl(this.returnToReview ? '/student/review' : '/student/study-preferences');
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        localStorage.removeItem('superoffer_access_token');
        sessionStorage.removeItem('superoffer_access_token');
        this.router.navigate(['/auth/login/student'], { queryParams: { sessionExpired: '1' } });
        return;
      }
      this.saveError = e instanceof Error ? e.message : 'Could not save your details. Please try again.';
    } finally {
      this.saving = false;
      this.cdr.detectChanges();
    }
  }
}

// components/student/PersonalInformation.tsx
'use client';

import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { authApi, type ApiError } from '@/lib/api/auth-api';
import { useSectionFields } from '@/lib/forms/use-section-fields';
import { classNames } from '@/lib/cx';
import type { CountryInfo } from '@/lib/options/geo';
import { clearAccessToken, readAccessToken } from '@/lib/storage';
import { useFormSection, validateField } from '@/lib/forms/use-form-schema';
import { useStudentProfile } from '@/lib/stores/student-profile.store';
import styles from '@/styles/PersonalInformation.module.css';
import { SchemaFields } from './SchemaFields';

const cx = classNames(styles);

export function PersonalInformation() {
  const profile = useStudentProfile();
  const router = useRouter();
  const searchParams = useSearchParams();
  const returnToReview = searchParams.get('from') === 'review';

  const [countries, setCountries] = useState<CountryInfo[]>([]);
  const [countryCityOptions, setCountryCityOptions] = useState<Record<string, string[]>>({});
  const [countryOpen, setCountryOpen] = useState(false);
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [submitted, setSubmitted] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');

  const [form, setForm] = useState<Record<string, string>>({ mobileCountry: 'IN', altMobileCountry: 'IN' });
  const seeded = useRef(false);

  /**
   * The fields this step draws by hand, so the schema renderer only adds what an
   * admin has introduced rather than duplicating them.
   */
  const CODED_KEYS = [
    'fullName', 'email', 'mobileCountry', 'mobileNumber',
    'altMobileCountry', 'altMobileNumber', 'country', 'city', 'phone', 'location'
  ];

  /** What the published form says about the fields drawn by hand above. */
  const fields = useSectionFields('personalInformation', CODED_KEYS);

  const { fields: schemaFields } = useFormSection('personalInformation');
  const extraFields = schemaFields.filter(field => !CODED_KEYS.includes(field.key) && !field.composite);
  const [extraValues, setExtraValues] = useState<Record<string, unknown>>({});
  const [extraTouched, setExtraTouched] = useState<Record<string, boolean>>({});

  const value = (key: string) => form[key] || '';
  const setValue = (key: string, next: string) => setForm(current => ({ ...current, [key]: next }));

  /** Seed the form once from whatever the server already holds for this section. */
  useEffect(() => {
    if (seeded.current || !profile.loaded) return;
    seeded.current = true;
    setForm(current => ({ ...current, ...profile.profile.personal }));
    /** Admin-added fields live in the same section, so they seed from it too. */
    setExtraValues(current => ({ ...profile.profile.personal, ...current }));
  }, [profile.loaded, profile.profile.personal]);

  const handleUnauthorized = () => {
    clearAccessToken();
    router.push('/auth/login/student?sessionExpired=1');
  };

  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      const token = readAccessToken();
      if (!token) {
        router.push('/auth/login/student');
        return;
      }
      try {
        const geo = await authApi.getGeoReferenceData();
        if (cancelled) return;
        setCountries(geo.countries);
        setCountryCityOptions({ India: geo.indiaCities });
      } catch {
        // Reference data endpoint unreachable — dropdowns stay empty; the student can still type a country/city.
      }
    };

    void load();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const markTouched = (key: string) => setTouched(current => ({ ...current, [key]: true }));

  const fullNameError = value('fullName').trim().length >= 2 ? '' : 'Enter your full name';

  const emailError = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value('email').trim()) ? '' : 'Enter a valid email address';

  const mobileError = (() => {
    if (!value('mobileCountry')) return 'Select a country code';
    const digits = value('mobileNumber').replace(/\D/g, '');
    return /^\d{6,14}$/.test(digits) ? '' : 'Enter a valid mobile number';
  })();

  const altMobileError = (() => {
    const raw = value('altMobileNumber').trim();
    if (!raw) return '';
    if (!value('altMobileCountry')) return 'Select a country code';
    const digits = raw.replace(/\D/g, '');
    return /^\d{6,14}$/.test(digits) ? '' : 'Enter a valid mobile number';
  })();

  const countryValid = countries.some(c => c.name === value('country'));
  const countryError = countryValid ? '' : 'Select a valid country from the list';

  const cityOptions = countryCityOptions[value('country')] || [];
  const hasCityOptions = cityOptions.length > 0;
  const cityError = value('city').trim() ? '' : 'Select or enter your current city';

  /** The published field each hand-drawn control saves into. */
  const SCHEMA_KEY: Record<string, string> = {
    fullName: 'fullName',
    email: 'email',
    mobile: 'mobileNumber',
    altMobile: 'altMobileNumber',
    country: 'country',
    city: 'city'
  };

  const errorFor = (key: string): string => {
    /** A field the admin has hidden cannot be wrong, and must not block the step. */
    if (SCHEMA_KEY[key] && !fields.shows(SCHEMA_KEY[key])) return '';

    switch (key) {
      case 'fullName': return fullNameError;
      case 'email': return emailError;
      case 'mobile': return mobileError;
      case 'altMobile': return altMobileError;
      case 'country': return countryError;
      case 'city': return cityError;
      default: return '';
    }
  };

  const showError = (key: string) => (touched[key] || submitted) && !!errorFor(key);

  const filteredCountries = (() => {
    const query = value('country').trim().toLowerCase();
    return !query ? countries : countries.filter(c => c.name.toLowerCase().includes(query));
  })();

  const selectCountry = (country: CountryInfo) => {
    const changed = value('country') !== country.name;
    setValue('country', country.name);
    setCountryOpen(false);
    if (changed) setValue('city', '');
  };

  const isValid = !Object.keys(SCHEMA_KEY).some(key => errorFor(key));

  const dialFor = (iso2: string) => countries.find(c => c.iso2 === iso2)?.dial || '';

  /** The same rules the server will apply, so problems surface before the round trip. */
  const extraErrors = Object.fromEntries(
    extraFields.map(field => [field.key, validateField(field, extraValues[field.key])])
  );
  const extraValid = Object.values(extraErrors).every(message => !message);

  const saveAndContinue = async () => {
    setSubmitted(true);
    setSaveError('');
    /** Touch every added field so its error is visible rather than silent. */
    setExtraTouched(Object.fromEntries(extraFields.map(field => [field.key, true])));
    if (!isValid || !extraValid) return;

    const token = readAccessToken();
    if (!token) {
      router.push('/auth/login/student');
      return;
    }

    const mobile = `${dialFor(value('mobileCountry'))} ${value('mobileNumber')}`.trim();

    const payload = {
      ...extraValues,
      fullName: value('fullName'),
      email: value('email'),
      mobileCountry: value('mobileCountry'),
      mobileNumber: value('mobileNumber'),
      altMobileCountry: value('altMobileCountry') || undefined,
      altMobileNumber: value('altMobileNumber') || undefined,
      country: value('country'),
      city: value('city'),
      phone: mobile,
      location: [value('city'), value('country')].filter(Boolean).join(', ')
    };

    setSaving(true);
    try {
      await authApi.saveStudentPersonalInformation(token, payload);
      await profile.refresh();
      router.push(returnToReview ? '/student/review' : '/student/study-preferences');
    } catch (e) {
      if ((e as ApiError).status === 401) {
        handleUnauthorized();
        return;
      }
      setSaveError(e instanceof Error ? e.message : 'Could not save your details. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const dialOptions = countries.map(c => (
    <option key={c.iso2} value={c.iso2} title={c.name}>{c.dial}</option>
  ));

  return (
    <div className={cx('host')}>
      <section className={cx('step-page')}>
        <div className={cx('profile-form-card')}>
          <div className={cx('card-head')}>
            <div className={cx('placeholder-copy')}>
              <div>
                <h2>{fields.title || 'Personal Information'} details</h2>
                <p>{fields.description || 'Your information is securely saved to your student profile.'}</p>
              </div>
            </div>
            <span className={cx('step-badge')}>STEP 1 OF 9</span>
          </div>

          <div className={cx('field-grid')}>
            {!!extraFields.length && (
              <SchemaFields
                fields={extraFields}
                values={extraValues}
                errors={extraErrors}
                touched={extraTouched}
                cx={cx}
                onChange={(key, value) => setExtraValues(current => ({ ...current, [key]: value }))}
                onBlur={key => setExtraTouched(current => ({ ...current, [key]: true }))}
              />
            )}

            {fields.shows('fullName') && (
              <label className={cx(showError('fullName') && 'field-invalid')}>
                <span className={cx('field-label')}>{fields.labelOf('fullName', 'Full Name')}{fields.isRequired('fullName', true) && <span className={cx('required-mark')}> *</span>}</span>
                <input
                  type="text" name="fullName" autoComplete="name" placeholder="Aarav Mehta"
                  value={value('fullName')}
                  onChange={e => setValue('fullName', e.target.value)}
                  onBlur={() => markTouched('fullName')}
                />
                {showError('fullName') && <small className={cx('field-error')}>{fullNameError}</small>}
              </label>
            )}

            {fields.shows('email') && (
              <label className={cx(showError('email') && 'field-invalid')}>
                <span className={cx('field-label')}>{fields.labelOf('email', 'Email Address')}{fields.isRequired('email', true) && <span className={cx('required-mark')}> *</span>}</span>
                <input
                  type="email" name="email" autoComplete="email" placeholder="aarav@example.com"
                  value={value('email')}
                  onChange={e => setValue('email', e.target.value)}
                  onBlur={() => markTouched('email')}
                />
                {showError('email') && <small className={cx('field-error')}>{emailError}</small>}
              </label>
            )}

            <div className={cx('field-pair-row')}>
              {fields.shows('mobileNumber') && (
                <label className={cx(showError('mobile') && 'field-invalid')}>
                  <span className={cx('field-label')}>{fields.labelOf('mobileNumber', 'Mobile Number')}{fields.isRequired('mobileNumber', true) && <span className={cx('required-mark')}> *</span>}</span>
                  <div className={cx('phone-group')}>
                    <select
                      className={cx('dial-select')} name="mobileCountry"
                      value={value('mobileCountry')}
                      onChange={e => { setValue('mobileCountry', e.target.value); markTouched('mobile'); }}
                      onBlur={() => markTouched('mobile')}
                    >
                      <option value="" disabled>+</option>
                      {dialOptions}
                    </select>
                    <input
                      type="tel" name="mobileNumber" autoComplete="tel-national" placeholder="98765 43210"
                      value={value('mobileNumber')}
                      onChange={e => setValue('mobileNumber', e.target.value)}
                      onBlur={() => markTouched('mobile')}
                    />
                  </div>
                  {showError('mobile')
                    ? <small className={cx('field-error')}>{mobileError}</small>
                    : <small className={cx('field-hint')}>&nbsp;</small>}
                </label>
              )}

              {fields.shows('altMobileNumber') && (
                <label className={cx(showError('altMobile') && 'field-invalid')}>
                  <span className={cx('field-label')}>{fields.labelOf('altMobileNumber', 'Additional Mobile Number')}{fields.isRequired('altMobileNumber', false) && <span className={cx('required-mark')}> *</span>}</span>
                  <div className={cx('phone-group')}>
                    <select
                      className={cx('dial-select')} name="altMobileCountry"
                      value={value('altMobileCountry')}
                      onChange={e => { setValue('altMobileCountry', e.target.value); markTouched('altMobile'); }}
                      onBlur={() => markTouched('altMobile')}
                    >
                      <option value="" disabled>+</option>
                      {dialOptions}
                    </select>
                    <input
                      type="tel" name="altMobileNumber" autoComplete="tel-national" placeholder="Optional"
                      value={value('altMobileNumber')}
                      onChange={e => setValue('altMobileNumber', e.target.value)}
                      onBlur={() => markTouched('altMobile')}
                    />
                  </div>
                  {showError('altMobile')
                    ? <small className={cx('field-error')}>{altMobileError}</small>
                    : <small className={cx('field-hint')}>&nbsp;</small>}
                </label>
              )}
            </div>

            <div className={cx('field-pair-row')}>
              {fields.shows('country') && (
                <label className={cx('combo-field', showError('country') && 'field-invalid')}>
                  <span className={cx('field-label')}>{fields.labelOf('country', 'Country')}{fields.isRequired('country', true) && <span className={cx('required-mark')}> *</span>}</span>
                  <input
                    type="text" name="country" autoComplete="country-name" placeholder="Search for your country"
                    value={value('country')}
                    onFocus={() => setCountryOpen(true)}
                    onChange={e => { setValue('country', e.target.value); setCountryOpen(true); }}
                    onBlur={() => setTimeout(() => setCountryOpen(false), 150)}
                  />
                  {countryOpen && (
                    <ul className={cx('combo-list')}>
                      {filteredCountries.map(c => (
                        <li key={c.iso2} onMouseDown={() => selectCountry(c)}>{c.name}</li>
                      ))}
                      {!filteredCountries.length && <li className={cx('combo-empty')}>No matching country</li>}
                    </ul>
                  )}
                  {showError('country') && <small className={cx('field-error')}>{countryError}</small>}
                </label>
              )}

              {fields.shows('city') && (
                <label className={cx(showError('city') && 'field-invalid')}>
                  <span className={cx('field-label')}>{fields.labelOf('city', 'Current City')}{fields.isRequired('city', true) && <span className={cx('required-mark')}> *</span>}</span>
                  {hasCityOptions ? (
                    <select
                      name="city"
                      value={value('city')}
                      onChange={e => { setValue('city', e.target.value); markTouched('city'); }}
                      onBlur={() => markTouched('city')}
                    >
                      <option value="" disabled>Select city</option>
                      {cityOptions.map(city => <option key={city} value={city}>{city}</option>)}
                    </select>
                  ) : (
                    <input
                      type="text" name="city" placeholder="Enter your current city"
                      value={value('city')}
                      disabled={!countryValid}
                      onChange={e => setValue('city', e.target.value)}
                      onBlur={() => markTouched('city')}
                    />
                  )}
                  {!countryValid && <small className={cx('field-hint')}>Select a valid country first</small>}
                  {countryValid && !hasCityOptions && (
                    <small className={cx('field-hint')}>City list not available for this country — type your city</small>
                  )}
                  {showError('city') && <small className={cx('field-error')}>{cityError}</small>}
                </label>
              )}
            </div>
          </div>

          {submitted && !isValid && (
            <p className={cx('save-message', 'error')}>Please fix the highlighted fields before continuing.</p>
          )}
          {saveError && <p className={cx('save-message', 'error')}>{saveError}</p>}
        </div>

        <div className={cx('step-actions')}>
          <span></span>
          <button className={cx('button', 'primary')} type="button" disabled={saving} onClick={saveAndContinue}>
            {saving ? 'Saving…' : 'Continue'}
          </button>
        </div>
      </section>
    </div>
  );
}
