// src/app/pages/student-portal/study-preferences.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, ReactiveFormsModule, ValidationErrors } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { StudentProfileUiStore } from './student-profile-ui.store';
import { AuthApiService } from '../../core/auth-api.service';

type MultiKey = 'countries' | 'fieldsOfStudy' | 'programs' | 'startYear' | 'intakes';
type Which = 'country' | 'field' | 'program' | 'intake' | 'year';

function requireOne(control: AbstractControl): ValidationErrors | null {
  return Array.isArray(control.value) && control.value.length ? null : { required: true };
}

@Component({
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  styleUrl: './study-preferences.css',
  template: `
    <section class="step-page">
      <form class="profile-form-card" [formGroup]="form" (ngSubmit)="saveAndContinue()">
        <div class="card-head">
          <div class="placeholder-copy">
            <div>
              <h2>Study Preferences details</h2>
              <p>Your information is securely saved to your student profile.</p>
            </div>
          </div>
          <span class="step-badge">STEP 2 OF 9</span>
        </div>

        <div class="field-grid">
          <div class="combo-field wide" [class.field-invalid]="showError('countries')">
            <span class="field-label">Which country do you want to study in? <span class="required-mark">*</span></span>
            <div class="combo-input-wrap">
              <span class="tag-chip" *ngFor="let item of selectedOf('countries')">{{item}}<button type="button" (mousedown)="$event.preventDefault()" (click)="toggleMulti('countries', item)" [attr.aria-label]="'Remove '+item">×</button></span>
              <input #countryBox type="text" placeholder="Search countries"
                [value]="countryOpen ? countryQuery : ''"
                (focus)="onFieldFocus('country')" (input)="onFieldInput('country', $any($event.target).value)" (blur)="delayedClose('country')">
              <button type="button" class="combo-arrow" [class.open]="countryOpen" (mousedown)="$event.preventDefault()" (click)="toggleOpen('country', countryBox)" aria-label="Toggle country list">▾</button>
            </div>
            <ul class="combo-list" *ngIf="countryOpen" (mousedown)="$event.preventDefault()">
              <li *ngFor="let opt of filterOptions(countryOptions, countryQuery)" (click)="toggleMulti('countries', opt)">
                <span class="option-check" [class.checked]="isSelected('countries', opt)">✓</span>{{opt}}
              </li>
              <li class="combo-empty" *ngIf="!filterOptions(countryOptions, countryQuery).length">No matching country</li>
            </ul>
            <small class="field-error" *ngIf="showError('countries')">Select at least one country</small>
          </div>

          <div class="combo-field wide" [class.field-invalid]="showError('fieldsOfStudy')">
            <span class="field-label">What do you want to study? <span class="required-mark">*</span></span>
            <div class="combo-input-wrap">
              <span class="tag-chip" *ngFor="let item of selectedOf('fieldsOfStudy')">{{item}}<button type="button" (mousedown)="$event.preventDefault()" (click)="toggleMulti('fieldsOfStudy', item)" [attr.aria-label]="'Remove '+item">×</button></span>
              <input #fieldBox type="text" placeholder="Search"
                [value]="fieldOpen ? fieldQuery : ''"
                (focus)="onFieldFocus('field')" (input)="onFieldInput('field', $any($event.target).value)" (blur)="delayedClose('field')">
              <button type="button" class="combo-arrow" [class.open]="fieldOpen" (mousedown)="$event.preventDefault()" (click)="toggleOpen('field', fieldBox)" aria-label="Toggle list">▾</button>
            </div>
            <ul class="combo-list" *ngIf="fieldOpen" (mousedown)="$event.preventDefault()">
              <li *ngFor="let opt of filterOptions(availableFieldOptions(), fieldQuery)" (click)="toggleMulti('fieldsOfStudy', opt)">
                <span class="option-check" [class.checked]="isSelected('fieldsOfStudy', opt)">✓</span>{{opt}}
              </li>
              <li class="combo-empty" *ngIf="!filterOptions(availableFieldOptions(), fieldQuery).length">No matching option</li>
            </ul>
            <small class="field-hint" *ngIf="isMbbsOnlyCountrySelected()">One of your selected countries only offers MBBS.</small>
            <small class="field-error" *ngIf="showError('fieldsOfStudy')">Select at least one option</small>
          </div>

          <div class="combo-field wide" [class.field-invalid]="showError('programs')">
            <span class="field-label">Program of Interest <span class="required-mark">*</span></span>
            <div class="combo-input-wrap">
              <span class="tag-chip" *ngFor="let item of selectedOf('programs')">{{item}}<button type="button" (mousedown)="$event.preventDefault()" (click)="toggleMulti('programs', item)" [attr.aria-label]="'Remove '+item">×</button></span>
              <input #programBox type="text" placeholder="Search programs"
                [value]="programOpen ? programQuery : ''"
                (focus)="onFieldFocus('program')" (input)="onFieldInput('program', $any($event.target).value)" (blur)="delayedClose('program')">
              <button type="button" class="combo-arrow" [class.open]="programOpen" (mousedown)="$event.preventDefault()" (click)="toggleOpen('program', programBox)" aria-label="Toggle program list">▾</button>
            </div>
            <ul class="combo-list" *ngIf="programOpen" (mousedown)="$event.preventDefault()">
              <li *ngFor="let opt of filterOptions(programOptions, programQuery)" (click)="toggleMulti('programs', opt)">
                <span class="option-check" [class.checked]="isSelected('programs', opt)">✓</span>{{opt}}
              </li>
              <li class="combo-empty" *ngIf="!filterOptions(programOptions, programQuery).length">No matching program</li>
            </ul>
            <small class="field-error" *ngIf="showError('programs')">Select at least one program</small>
          </div>

          <div class="combo-field wide" [class.field-invalid]="showError('startYear')">
            <span class="field-label">When do you plan to start studying? <span class="required-mark">*</span></span>
            <div class="combo-input-wrap">
              <span class="tag-chip" *ngFor="let item of selectedOf('startYear')">{{item}}<button type="button" (mousedown)="$event.preventDefault()" (click)="toggleMulti('startYear', item)" [attr.aria-label]="'Remove '+item">×</button></span>
              <input #yearBox type="text" placeholder="Search year"
                [value]="yearOpen ? yearQuery : ''"
                (focus)="onFieldFocus('year')" (input)="onFieldInput('year', $any($event.target).value)" (blur)="delayedClose('year')">
              <button type="button" class="combo-arrow" [class.open]="yearOpen" (mousedown)="$event.preventDefault()" (click)="toggleOpen('year', yearBox)" aria-label="Toggle year list">▾</button>
            </div>
            <ul class="combo-list" *ngIf="yearOpen" (mousedown)="$event.preventDefault()">
              <li *ngFor="let year of filterYearOptions(yearQuery)" (click)="toggleMulti('startYear', '' + year)">
                <span class="option-check" [class.checked]="isSelected('startYear', '' + year)">✓</span>{{year}}
              </li>
              <li class="combo-empty" *ngIf="!filterYearOptions(yearQuery).length">No matching year</li>
            </ul>
            <small class="field-error" *ngIf="showError('startYear')">Select at least one start year</small>
          </div>

          <div class="combo-field wide" [class.field-invalid]="showError('intakes')">
            <span class="field-label">Preferred Intake <span class="required-mark">*</span></span>
            <div class="combo-input-wrap">
              <span class="tag-chip" *ngFor="let item of selectedOf('intakes')">{{item}}<button type="button" (mousedown)="$event.preventDefault()" (click)="toggleMulti('intakes', item)" [attr.aria-label]="'Remove '+item">×</button></span>
              <input #intakeBox type="text" placeholder="Search intake"
                [value]="intakeOpen ? intakeQuery : ''"
                (focus)="onFieldFocus('intake')" (input)="onFieldInput('intake', $any($event.target).value)" (blur)="delayedClose('intake')">
              <button type="button" class="combo-arrow" [class.open]="intakeOpen" (mousedown)="$event.preventDefault()" (click)="toggleOpen('intake', intakeBox)" aria-label="Toggle intake list">▾</button>
            </div>
            <ul class="combo-list" *ngIf="intakeOpen" (mousedown)="$event.preventDefault()">
              <li *ngFor="let opt of filterOptions(intakeOptions, intakeQuery)" (click)="toggleMulti('intakes', opt)">
                <span class="option-check" [class.checked]="isSelected('intakes', opt)">✓</span>{{opt}}
              </li>
              <li class="combo-empty" *ngIf="!filterOptions(intakeOptions, intakeQuery).length">No matching intake</li>
            </ul>
            <small class="field-error" *ngIf="showError('intakes')">Select at least one intake</small>
          </div>
        </div>

        <p class="save-message error" *ngIf="submitted && form.invalid">Please fix the highlighted fields before continuing.</p>
        <p class="save-message error" *ngIf="saveError">{{saveError}}</p>
      </form>

      <div class="step-actions">
        <a class="button secondary" routerLink="/student/personal-information">Previous</a>
        <button class="button primary" type="button" [disabled]="saving" (click)="saveAndContinue()">{{saving ? 'Saving…' : 'Continue'}}</button>
      </div>
    </section>
  `
})
export class StudyPreferencesComponent implements OnInit {
  countryOptions: string[] = [];
  mbbsOnlyCountries: string[] = [];
  /** "What do you want to study?" — MBBS-only for MBBS-only countries, the full subject list otherwise. */
  fieldOptions: string[] = [];
  /** "Program of Interest" — always the full subject list. */
  programOptions: string[] = [];
  intakeOptions: string[] = [];
  startYearOptions: number[] = [];

  countryQuery = '';
  fieldQuery = '';
  programQuery = '';
  intakeQuery = '';
  yearQuery = '';
  countryOpen = false;
  fieldOpen = false;
  programOpen = false;
  intakeOpen = false;
  yearOpen = false;
  submitted = false;
  saving = false;
  saveError = '';

  form = this.fb.nonNullable.group({
    countries: this.fb.nonNullable.control<string[]>([], requireOne),
    fieldsOfStudy: this.fb.nonNullable.control<string[]>([], requireOne),
    programs: this.fb.nonNullable.control<string[]>([], requireOne),
    startYear: this.fb.nonNullable.control<string[]>([], requireOne),
    intakes: this.fb.nonNullable.control<string[]>([], requireOne)
  });

  private returnToReview = false;

  constructor(
    private fb: FormBuilder,
    public store: StudentProfileUiStore,
    private router: Router,
    private route: ActivatedRoute,
    private api: AuthApiService,
    private cdr: ChangeDetectorRef
  ) {
    this.form.patchValue({
      countries: this.splitList(this.store.values['countries']),
      fieldsOfStudy: this.splitList(this.store.values['studyLevel']),
      programs: this.splitList(this.store.values['fieldOfInterest']),
      startYear: this.splitList(this.store.values['startYear']),
      intakes: this.splitList(this.store.values['intake'])
    });
    this.returnToReview = this.route.snapshot.queryParamMap.get('from') === 'review';
  }

  private getToken(): string | null {
    return localStorage.getItem('superoffer_access_token') || sessionStorage.getItem('superoffer_access_token');
  }

  async ngOnInit() {
    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }
    try {
      const options = await this.api.getStudyPreferencesReferenceData();
      this.countryOptions = options.studyCountries;
      this.mbbsOnlyCountries = options.mbbsOnlyCountries;
      this.fieldOptions = options.fieldsOfStudy;
      this.programOptions = options.fieldsOfStudy;
      this.intakeOptions = options.intakeOptions;
      this.startYearOptions = options.startYears.map(Number);
    } catch {
      // Reference data endpoint unreachable — dropdowns stay empty; existing selections still load below.
    }
    try {
      const profile = await this.api.studentProfile(token);
      const prefs = (profile?.studyPreferences as Record<string, string[]>) || {};
      if (!this.selectedOf('countries').length && prefs['countries']?.length) {
        this.form.patchValue({
          countries: prefs['countries'] || [],
          fieldsOfStudy: prefs['studyLevel'] || [],
          programs: prefs['fieldOfInterest'] || [],
          startYear: prefs['startYear'] || [],
          intakes: prefs['intake'] || []
        });
        this.syncStoreFromForm();
      }
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        localStorage.removeItem('superoffer_access_token');
        sessionStorage.removeItem('superoffer_access_token');
        this.router.navigate(['/auth/login/student'], { queryParams: { sessionExpired: '1' } });
        return;
      }
      // No saved preferences yet, or the server is unreachable — the student can still fill the form from scratch.
    }
    this.cdr.detectChanges();
  }

  private splitList(value?: string): string[] {
    return (value || '').split(',').map(item => item.trim()).filter(Boolean);
  }

  /** Keeps the flat local store (read by review-profile/dashboard) in sync with the form's arrays. */
  private syncStoreFromForm() {
    const value = this.form.getRawValue();
    this.store.values['countries'] = value.countries.join(', ');
    this.store.values['studyLevel'] = value.fieldsOfStudy.join(', ');
    this.store.values['fieldOfInterest'] = value.programs.join(', ');
    this.store.values['startYear'] = value.startYear.join(', ');
    this.store.values['intake'] = value.intakes.join(', ');
  }

  selectedOf(key: MultiKey): string[] { return this.form.get(key)!.value as string[]; }
  isSelected(key: MultiKey, value: string): boolean { return this.selectedOf(key).includes(value); }

  /** Every combo field allows multiple selections; dropdown stays open so more picks can follow. */
  toggleMulti(key: MultiKey, value: string) {
    const control = this.form.get(key)!;
    const current: string[] = control.value || [];
    const next = current.includes(value) ? current.filter(item => item !== value) : [...current, value];
    control.setValue(next);
    control.markAsTouched();
    this.resetQuery(key);

    if (key === 'countries') this.syncFieldsOfStudyForCountries();
  }

  /** True once one of the selected countries only offers an MBBS pathway. */
  isMbbsOnlyCountrySelected(): boolean {
    return this.selectedOf('countries').some(country => this.mbbsOnlyCountries.includes(country));
  }

  /** "What do you want to study?" narrows to MBBS only once an MBBS-only country is picked. */
  availableFieldOptions(): string[] {
    return this.isMbbsOnlyCountrySelected() ? ['MBBS'] : this.fieldOptions;
  }

  /** Drops study levels no longer offered, and auto-fills MBBS once an MBBS-only country is picked. */
  private syncFieldsOfStudyForCountries() {
    const allowed = this.availableFieldOptions();
    const control = this.form.get('fieldsOfStudy')!;
    const current: string[] = control.value || [];
    let next = current.filter(item => allowed.includes(item));
    if (this.isMbbsOnlyCountrySelected() && !next.includes('MBBS')) next = [...next, 'MBBS'];
    if (next.length !== current.length || next.some((item, i) => item !== current[i])) control.setValue(next);
  }


  /** Clears the search text so the box falls back to showing the (now updated) selection. */
  private resetQuery(key: MultiKey) {
    if (key === 'countries') this.countryQuery = '';
    else if (key === 'fieldsOfStudy') this.fieldQuery = '';
    else if (key === 'programs') this.programQuery = '';
    else if (key === 'startYear') this.yearQuery = '';
    else this.intakeQuery = '';
  }

  filterOptions(options: string[], query: string): string[] {
    const q = query.trim().toLowerCase();
    return !q ? options : options.filter(option => option.toLowerCase().includes(q));
  }

  filterYearOptions(query: string): number[] {
    const q = query.trim();
    return !q ? this.startYearOptions : this.startYearOptions.filter(year => String(year).includes(q));
  }

  /** Closes the dropdown when focus genuinely leaves the field (option clicks don't blur it). */
  delayedClose(which: Which) {
    if (which === 'country') this.countryOpen = false;
    else if (which === 'field') this.fieldOpen = false;
    else if (which === 'program') this.programOpen = false;
    else if (which === 'intake') this.intakeOpen = false;
    else this.yearOpen = false;
  }

  onFieldFocus(which: Which) {
    if (which === 'country') { this.countryOpen = true; this.countryQuery = ''; }
    else if (which === 'field') { this.fieldOpen = true; this.fieldQuery = ''; }
    else if (which === 'program') { this.programOpen = true; this.programQuery = ''; }
    else if (which === 'intake') { this.intakeOpen = true; this.intakeQuery = ''; }
    else { this.yearOpen = true; this.yearQuery = ''; }
  }

  isOpen(which: Which): boolean {
    if (which === 'country') return this.countryOpen;
    if (which === 'field') return this.fieldOpen;
    if (which === 'program') return this.programOpen;
    if (which === 'intake') return this.intakeOpen;
    return this.yearOpen;
  }

  /** Lets the dropdown arrow open/close the list without needing to click into the text box first. */
  toggleOpen(which: Which, inputEl: HTMLInputElement) {
    if (this.isOpen(which)) {
      this.delayedClose(which);
      inputEl.blur();
    } else {
      this.onFieldFocus(which);
      inputEl.focus();
    }
  }

  onFieldInput(which: Which, value: string) {
    if (which === 'country') this.countryQuery = value;
    else if (which === 'field') this.fieldQuery = value;
    else if (which === 'program') this.programQuery = value;
    else if (which === 'intake') this.intakeQuery = value;
    else this.yearQuery = value;
  }

  showError(key: MultiKey): boolean {
    const control = this.form.get(key)!;
    return (control.touched || this.submitted) && control.invalid;
  }

  async saveAndContinue() {
    this.submitted = true;
    this.saveError = '';
    this.form.markAllAsTouched();
    if (this.form.invalid) return;

    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }

    const value = this.form.getRawValue();
    const payload = {
      countries: value.countries,
      studyLevel: value.fieldsOfStudy,
      fieldOfInterest: value.programs,
      startYear: value.startYear,
      intake: value.intakes
    };

    this.saving = true;
    try {
      await this.api.saveStudentStudyPreferences(token, payload);
      this.syncStoreFromForm();
      this.router.navigateByUrl(this.returnToReview ? '/student/review' : '/student/academic-information');
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        localStorage.removeItem('superoffer_access_token');
        sessionStorage.removeItem('superoffer_access_token');
        this.router.navigate(['/auth/login/student'], { queryParams: { sessionExpired: '1' } });
        return;
      }
      this.saveError = e instanceof Error ? e.message : 'Could not save your preferences. Please try again.';
    } finally {
      this.saving = false;
      this.cdr.detectChanges();
    }
  }
}

// components/student/StudyPreferences.tsx
'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { authApi, type ApiError } from '@/lib/api/auth-api';
import { classNames } from '@/lib/cx';
import { clearAccessToken, readAccessToken } from '@/lib/storage';
import { useSchemaExtras } from '@/lib/forms/use-schema-extras';
import { useStudentProfile } from '@/lib/stores/student-profile.store';
import styles from '@/styles/StudyPreferences.module.css';
import { SchemaFields } from './SchemaFields';
import { useSectionFields } from '@/lib/forms/use-section-fields';
import { MultiComboField } from './MultiComboField';

const cx = classNames(styles);

type MultiKey = 'countries' | 'fieldsOfStudy' | 'programs' | 'startYear' | 'intakes';
type Which = 'country' | 'field' | 'program' | 'intake' | 'year';

type Selections = Record<MultiKey, string[]>;

/** The keys this step draws itself; anything else published is an addition. */
const CODED_KEYS = ['countries', 'studyLevel', 'fieldOfInterest', 'startYear', 'intake'];

const EMPTY: Selections = { countries: [], fieldsOfStudy: [], programs: [], startYear: [], intakes: [] };

/** Which published field each selection on this page saves into. */
const SCHEMA_KEY: Record<MultiKey, string> = {
  countries: 'countries',
  fieldsOfStudy: 'studyLevel',
  programs: 'fieldOfInterest',
  startYear: 'startYear',
  intakes: 'intake'
};

const QUERY_KEY: Record<MultiKey, Which> = {
  countries: 'country',
  fieldsOfStudy: 'field',
  programs: 'program',
  startYear: 'year',
  intakes: 'intake'
};

export function StudyPreferences() {
  const profile = useStudentProfile();
  const router = useRouter();
  const searchParams = useSearchParams();
  const returnToReview = searchParams.get('from') === 'review';

  const [countryOptions, setCountryOptions] = useState<string[]>([]);
  const [mbbsOnlyCountries, setMbbsOnlyCountries] = useState<string[]>([]);
  /** "What do you want to study?" — MBBS-only for MBBS-only countries, the full subject list otherwise. */
  const [fieldOptions, setFieldOptions] = useState<string[]>([]);
  /** "Program of Interest" — always the full subject list. */
  const [programOptions, setProgramOptions] = useState<string[]>([]);
  const [intakeOptions, setIntakeOptions] = useState<string[]>([]);
  const [startYearOptions, setStartYearOptions] = useState<number[]>([]);

  const [selections, setSelections] = useState<Selections>(EMPTY);
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [queries, setQueries] = useState<Record<Which, string>>({ country: '', field: '', program: '', intake: '', year: '' });
  const [openField, setOpenField] = useState<Which | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');
  const seeded = useRef(false);

  /** Fields this step draws by hand; anything else the schema declares is added below. */
  /** What the published form says about the fields this step draws by hand. */
  const fields = useSectionFields('studyPreferences', CODED_KEYS);

  const extras = useSchemaExtras(
    'studyPreferences',
    CODED_KEYS,
    profile.profile.studyPreferences,
    profile.loaded
  );


  const handleUnauthorized = () => {
    clearAccessToken();
    router.push('/auth/login/student?sessionExpired=1');
  };

  /** Seed once from the section the server already holds. */
  useEffect(() => {
    if (seeded.current || !profile.loaded) return;
    seeded.current = true;
    const saved = profile.profile.studyPreferences || {};
    setSelections({
      countries: saved['countries'] || [],
      fieldsOfStudy: saved['studyLevel'] || [],
      programs: saved['fieldOfInterest'] || [],
      startYear: saved['startYear'] || [],
      intakes: saved['intake'] || []
    });
  }, [profile.loaded, profile.profile.studyPreferences]);

  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      const token = readAccessToken();
      if (!token) {
        router.push('/auth/login/student');
        return;
      }
      try {
        const options = await authApi.getStudyPreferencesReferenceData();
        if (cancelled) return;
        setCountryOptions(options.studyCountries);
        setMbbsOnlyCountries(options.mbbsOnlyCountries);
        setFieldOptions(options.fieldsOfStudy);
        setProgramOptions(options.fieldsOfStudy);
        setIntakeOptions(options.intakeOptions);
        setStartYearOptions(options.startYears.map(Number));
      } catch {
        // Reference data endpoint unreachable — dropdowns stay empty; existing selections still load below.
      }
    };

    void load();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /** True once one of the selected countries only offers an MBBS pathway. */
  const isMbbsOnlyCountrySelected = (countries = selections.countries) =>
    countries.some(country => mbbsOnlyCountries.includes(country));

  /** "What do you want to study?" narrows to MBBS only once an MBBS-only country is picked. */
  const availableFieldOptions = (countries = selections.countries) =>
    isMbbsOnlyCountrySelected(countries) ? ['MBBS'] : fieldOptions;

  /** Every combo field allows multiple selections; dropdown stays open so more picks can follow. */
  const toggleMulti = (key: MultiKey, value: string) => {
    setSelections(current => {
      const list = current[key];
      const nextList = list.includes(value) ? list.filter(item => item !== value) : [...list, value];
      const next: Selections = { ...current, [key]: nextList };

      /** Drops study levels no longer offered, and auto-fills MBBS once an MBBS-only country is picked. */
      if (key === 'countries') {
        const allowed = availableFieldOptions(nextList);
        let fields = next.fieldsOfStudy.filter(item => allowed.includes(item));
        if (isMbbsOnlyCountrySelected(nextList) && !fields.includes('MBBS')) fields = [...fields, 'MBBS'];
        next.fieldsOfStudy = fields;
      }
      return next;
    });
    setTouched(current => ({ ...current, [key]: true }));
    /** Clears the search text so the box falls back to showing the (now updated) selection. */
    setQueries(current => ({ ...current, [QUERY_KEY[key]]: '' }));
  };

  const filterOptions = (options: string[], query: string): string[] => {
    const q = query.trim().toLowerCase();
    return !q ? options : options.filter(option => option.toLowerCase().includes(q));
  };

  const filterYearOptions = (query: string): string[] => {
    const q = query.trim();
    const years = startYearOptions.map(String);
    return !q ? years : years.filter(year => year.includes(q));
  };

  const openFor = (which: Which) => () => {
    setOpenField(which);
    setQueries(current => ({ ...current, [which]: '' }));
  };

  /** Closes the dropdown when focus genuinely leaves the field (option clicks don't blur it). */
  const closeFor = (which: Which) => () => setOpenField(current => (current === which ? null : current));

  const queryFor = (which: Which) => (value: string) => setQueries(current => ({ ...current, [which]: value }));

  /**
   * A field the admin has hidden or made optional cannot block the step. Only
   * what the published form still asks for is enforced here.
   */
  const invalid = (key: MultiKey) => {
    const published = SCHEMA_KEY[key];
    if (!fields.shows(published)) return false;
    if (!fields.isRequired(published, true)) return false;
    return !selections[key].length;
  };
  const showError = (key: MultiKey) => (touched[key] || submitted) && invalid(key);
  const formInvalid = (Object.keys(EMPTY) as MultiKey[]).some(invalid);

  const saveAndContinue = async () => {
    setSubmitted(true);
    extras.touchAll();
    setSaveError('');
    if (formInvalid) return;

    const token = readAccessToken();
    if (!token) {
      router.push('/auth/login/student');
      return;
    }

    const payload = {
      ...extras.values0,
      countries: selections.countries,
      studyLevel: selections.fieldsOfStudy,
      fieldOfInterest: selections.programs,
      startYear: selections.startYear,
      intake: selections.intakes
    };

    setSaving(true);
    try {
      await authApi.saveStudentStudyPreferences(token, payload);
      await profile.refresh();
      router.push(returnToReview ? '/student/review' : '/student/academic-information');
    } catch (e) {
      if ((e as ApiError).status === 401) {
        handleUnauthorized();
        return;
      }
      setSaveError(e instanceof Error ? e.message : 'Could not save your preferences. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const required = <span className={cx('required-mark')}>*</span>;

  return (
    <div className={cx('host')}>
      <section className={cx('step-page')}>
        <form className={cx('profile-form-card')} onSubmit={event => { event.preventDefault(); void saveAndContinue(); }}>
          <div className={cx('card-head')}>
            <div className={cx('placeholder-copy')}>
              <div>
                <h2>Study Preferences details</h2>
                <p>Your information is securely saved to your student profile.</p>
              </div>
            </div>
            <span className={cx('step-badge')}>STEP 2 OF 9</span>
          </div>

          <div className={cx('field-grid')}>
            {!!extras.fields.length && (
              <SchemaFields
                fields={extras.fields}
                values={extras.values}
                errors={extras.errors}
                touched={extras.touched}
                cx={cx}
                onChange={extras.setValue}
                onBlur={extras.setTouched}
              />
            )}


            {fields.shows('countries') && (
            <MultiComboField
              label={<>{fields.labelOf('countries', 'Which country do you want to study in?')}{fields.isRequired('countries', true) ? required : null}</>}
              placeholder="Search countries"
              toggleLabel="Toggle country list"
              emptyText="No matching country"
              options={filterOptions(countryOptions, queries.country)}
              selected={selections.countries}
              open={openField === 'country'}
              query={queries.country}
              invalid={showError('countries')}
              error="Select at least one country"
              onOpen={openFor('country')}
              onClose={closeFor('country')}
              onQueryChange={queryFor('country')}
              onToggleOption={value => toggleMulti('countries', value)}
            />
            )}

            {fields.shows('studyLevel') && (
            <MultiComboField
              label={<>{fields.labelOf('studyLevel', 'What do you want to study?')}{fields.isRequired('studyLevel', true) ? required : null}</>}
              placeholder="Search"
              toggleLabel="Toggle list"
              emptyText="No matching option"
              options={filterOptions(availableFieldOptions(), queries.field)}
              selected={selections.fieldsOfStudy}
              open={openField === 'field'}
              query={queries.field}
              invalid={showError('fieldsOfStudy')}
              error="Select at least one option"
              hint={
                isMbbsOnlyCountrySelected() ? (
                  <small className={cx('field-hint')}>One of your selected countries only offers MBBS.</small>
                ) : undefined
              }
              onOpen={openFor('field')}
              onClose={closeFor('field')}
              onQueryChange={queryFor('field')}
              onToggleOption={value => toggleMulti('fieldsOfStudy', value)}
            />
            )}

            {fields.shows('fieldOfInterest') && (
            <MultiComboField
              label={<>{fields.labelOf('fieldOfInterest', 'Program of Interest')}{fields.isRequired('fieldOfInterest', true) ? required : null}</>}
              placeholder="Search programs"
              toggleLabel="Toggle program list"
              emptyText="No matching program"
              options={filterOptions(programOptions, queries.program)}
              selected={selections.programs}
              open={openField === 'program'}
              query={queries.program}
              invalid={showError('programs')}
              error="Select at least one program"
              onOpen={openFor('program')}
              onClose={closeFor('program')}
              onQueryChange={queryFor('program')}
              onToggleOption={value => toggleMulti('programs', value)}
            />
            )}

            {fields.shows('startYear') && (
            <MultiComboField
              label={<>{fields.labelOf('startYear', 'When do you plan to start studying?')}{fields.isRequired('startYear', true) ? required : null}</>}
              placeholder="Search year"
              toggleLabel="Toggle year list"
              emptyText="No matching year"
              options={filterYearOptions(queries.year)}
              selected={selections.startYear}
              open={openField === 'year'}
              query={queries.year}
              invalid={showError('startYear')}
              error="Select at least one start year"
              onOpen={openFor('year')}
              onClose={closeFor('year')}
              onQueryChange={queryFor('year')}
              onToggleOption={value => toggleMulti('startYear', value)}
            />
            )}

            {fields.shows('intake') && (
            <MultiComboField
              label={<>{fields.labelOf('intake', 'Preferred Intake')}{fields.isRequired('intake', true) ? required : null}</>}
              placeholder="Search intake"
              toggleLabel="Toggle intake list"
              emptyText="No matching intake"
              options={filterOptions(intakeOptions, queries.intake)}
              selected={selections.intakes}
              open={openField === 'intake'}
              query={queries.intake}
              invalid={showError('intakes')}
              error="Select at least one intake"
              onOpen={openFor('intake')}
              onClose={closeFor('intake')}
              onQueryChange={queryFor('intake')}
              onToggleOption={value => toggleMulti('intakes', value)}
            />
            )}
          </div>

          {submitted && formInvalid && (
            <p className={cx('save-message', 'error')}>Please fix the highlighted fields before continuing.</p>
          )}
          {saveError && <p className={cx('save-message', 'error')}>{saveError}</p>}
        </form>

        <div className={cx('step-actions')}>
          <Link className={cx('button', 'secondary')} href="/student/personal-information">Previous</Link>
          <button className={cx('button', 'primary')} type="button" disabled={saving} onClick={saveAndContinue}>
            {saving ? 'Saving…' : 'Continue'}
          </button>
        </div>
      </section>
    </div>
  );
}
