// components/student/ReviewProfile.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState, type CSSProperties } from 'react';
import { authApi, type ApiError } from '@/lib/api/auth-api';
import { classNames } from '@/lib/cx';
import { clearAccessToken, readAccessToken } from '@/lib/storage';
import { useStudentProfile } from '@/lib/stores/student-profile.store';
import styles from '@/styles/ReviewProfile.module.css';

const cx = classNames(styles);

interface ExamEntry {
  exam: string;
  status: string;
  score: string;
  expectedScore: string;
  currentScore: string;
}

interface ProjectEntry {
  title: string;
  role: string;
  description: string;
}

/** Which completion sections each card on this page corresponds to. */
const SECTION_KEYS = {
  personal: 'personalInformation',
  study: 'studyPreferences',
  academic: 'academicInformation'
} as const;

export function ReviewProfile() {
  const profile = useStudentProfile();
  const router = useRouter();
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState('');

  const { personal, studyPreferences, academic, entranceExams, projects } = profile.profile;
  const { completionPercent, sections, missing } = profile.completion;

  const done = (key: string) => sections.find(section => section.key === key)?.done ?? false;

  const list = (value?: string[]) => (value || []).join(', ');
  const englishExams = (entranceExams['englishExams'] as ExamEntry[]) || [];
  const competitiveExams = (entranceExams['competitiveExams'] as ExamEntry[]) || [];
  const projectList = (projects['projects'] as ProjectEntry[]) || [];
  const achievements = (projects['achievements'] as string[]) || [];

  const examScoreSummary = (entry: ExamEntry): string => {
    if (entry.status === 'I have the score') return `Score: ${entry.score}`;
    if (entry.status === 'Retake') return `Current ${entry.currentScore} → Target ${entry.expectedScore}`;
    if (entry.expectedScore) return `Expected: ${entry.expectedScore}`;
    return entry.status;
  };

  const submitProfile = async () => {
    setSubmitError('');
    const token = readAccessToken();
    if (!token) {
      router.push('/auth/login/student');
      return;
    }

    setSubmitting(true);
    try {
      await authApi.submitStudentProfile(token);
      await profile.refresh();
      router.push('/student/dashboard');
    } catch (e) {
      if ((e as ApiError).status === 401) {
        clearAccessToken();
        router.push('/auth/login/student?sessionExpired=1');
        return;
      }
      setSubmitError(e instanceof Error ? e.message : 'Could not submit your profile. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  const statusPill = (complete: boolean) => (
    <span className={cx('section-status', complete ? 'ok' : 'warn')}>
      {complete ? '✓ Complete' : '⚠ Incomplete'}
    </span>
  );

  const summaryItem = (label: string, value?: string) => (
    <div className={cx('summary-item')} key={label}>
      <span>{label}</span>
      <strong className={cx(!value && 'empty')}>{value || 'Not added'}</strong>
    </div>
  );

  return (
    <div className={cx('host')}>
      <section className={cx('step-page')}>
        <div className={cx('completion-banner')}>
          <div className={cx('completion-ring')} style={{ '--pct': completionPercent } as CSSProperties}>
            <b>{completionPercent}%</b>
          </div>
          <div className={cx('completion-copy')}>
            <span>Profile Completion</span>
            <strong>{completionPercent}% Complete</strong>
            <p>
              {completionPercent === 100
                ? "Every required section is filled in — you're ready to submit."
                : 'Finish the sections below to unlock submission.'}
            </p>
            {!!missing.length && (
              <div className={cx('completion-missing')}>
                {missing.map(name => <span key={name}>{name}</span>)}
              </div>
            )}
          </div>
        </div>

        <div className={cx('section-grid')}>
          <div className={cx('section-card', !done(SECTION_KEYS.personal) && 'incomplete')}>
            <div className={cx('section-head')}>
              <span className={cx('section-icon')}>PI</span>
              <div className={cx('section-title-block')}>
                <h2>Personal Information</h2>
                {statusPill(done(SECTION_KEYS.personal))}
              </div>
              <Link className={cx('edit-btn')} href="/student/personal-information?from=review">Edit</Link>
            </div>
            <div className={cx('summary-list')}>
              {summaryItem('Full Name', personal['fullName'])}
              {summaryItem('Email', personal['email'])}
              {summaryItem('Mobile', personal['mobileNumber'])}
              {summaryItem('Country', personal['country'])}
              {summaryItem('City', personal['city'])}
            </div>
          </div>

          <div className={cx('section-card', !done(SECTION_KEYS.study) && 'incomplete')}>
            <div className={cx('section-head')}>
              <span className={cx('section-icon')}>SP</span>
              <div className={cx('section-title-block')}>
                <h2>Study Preferences</h2>
                {statusPill(done(SECTION_KEYS.study))}
              </div>
              <Link className={cx('edit-btn')} href="/student/study-preferences?from=review">Edit</Link>
            </div>
            <div className={cx('summary-list')}>
              {summaryItem('Countries', list(studyPreferences['countries']))}
              {summaryItem('Field of Study', list(studyPreferences['fieldOfInterest']))}
              {summaryItem('Program', list(studyPreferences['studyLevel']))}
              {summaryItem('Start Year', list(studyPreferences['startYear']))}
              {summaryItem('Preferred Intake', list(studyPreferences['intake']))}
            </div>
          </div>

          <div className={cx('section-card', !done(SECTION_KEYS.academic) && 'incomplete')}>
            <div className={cx('section-head')}>
              <span className={cx('section-icon')}>AC</span>
              <div className={cx('section-title-block')}>
                <h2>Academic Information</h2>
                {statusPill(done(SECTION_KEYS.academic))}
              </div>
              <Link className={cx('edit-btn')} href="/student/academic-information?from=review">Edit</Link>
            </div>
            <div className={cx('summary-list')}>
              {summaryItem('Highest Qualification', academic['qualificationLevel'] as string)}
              {summaryItem('Institution', academic['institution'] as string)}
              {summaryItem('CGPA / Percentage', academic['score'] as string)}
              {summaryItem('Completion Year', academic['graduationYear'] as string)}
            </div>
          </div>

          <div className={cx('section-card')}>
            <div className={cx('section-head')}>
              <span className={cx('section-icon')}>EN</span>
              <div className={cx('section-title-block')}>
                <h2>English Language Tests</h2>
                {!!englishExams.length && <span className={cx('section-status', 'ok')}>✓ {englishExams.length} added</span>}
              </div>
              <Link className={cx('edit-btn')} href="/student/english-exam?from=review">Edit</Link>
            </div>
            {!!englishExams.length && (
              <div className={cx('entry-list')}>
                {englishExams.map(entry => (
                  <div key={entry.exam} className={cx('entry-row')}>
                    <div><strong>{entry.exam}</strong><small>{entry.status}</small></div>
                    <span className={cx('entry-badge')}>{examScoreSummary(entry)}</span>
                  </div>
                ))}
              </div>
            )}
            {!englishExams.length && (
              <div className={cx('empty-state')}>
                <span className={cx('empty-icon')}>📝</span>
                <p>No English test recorded yet.</p>
                <Link className={cx('empty-cta')} href="/student/english-exam?from=review">+ Add now</Link>
              </div>
            )}
          </div>

          <div className={cx('section-card')}>
            <div className={cx('section-head')}>
              <span className={cx('section-icon')}>CE</span>
              <div className={cx('section-title-block')}>
                <h2>Standardized Tests</h2>
                {!!competitiveExams.length && <span className={cx('section-status', 'ok')}>✓ {competitiveExams.length} added</span>}
              </div>
              <Link className={cx('edit-btn')} href="/student/competitive-exam?from=review">Edit</Link>
            </div>
            {!!competitiveExams.length && (
              <div className={cx('entry-list')}>
                {competitiveExams.map(entry => (
                  <div key={entry.exam} className={cx('entry-row')}>
                    <div><strong>{entry.exam}</strong><small>{entry.status}</small></div>
                    <span className={cx('entry-badge')}>{examScoreSummary(entry)}</span>
                  </div>
                ))}
              </div>
            )}
            {!competitiveExams.length && (
              <div className={cx('empty-state')}>
                <span className={cx('empty-icon')}>🧮</span>
                <p>No standardized test recorded yet.</p>
                <Link className={cx('empty-cta')} href="/student/competitive-exam?from=review">+ Add now</Link>
              </div>
            )}
          </div>

          <div className={cx('section-card')}>
            <div className={cx('section-head')}>
              <span className={cx('section-icon')}>PA</span>
              <div className={cx('section-title-block')}>
                <h2>Projects &amp; Achievements</h2>
              </div>
              <Link className={cx('edit-btn')} href="/student/projects?from=review">Edit</Link>
            </div>
            {!!projectList.length && (
              <div className={cx('entry-list')}>
                {projectList.map((project, index) => (
                  <div key={`${project.title}-${index}`} className={cx('entry-row')}>
                    <div><strong>{project.title}</strong><small>{project.role}</small></div>
                  </div>
                ))}
              </div>
            )}
            {!!achievements.length && (
              <div className={cx('chip-row')}>
                {achievements.map(item => <span key={item} className={cx('chip')}>{item}</span>)}
              </div>
            )}
            {!projectList.length && !achievements.length && (
              <div className={cx('empty-state')}>
                <span className={cx('empty-icon')}>🏆</span>
                <p>No projects or achievements added yet.</p>
                <Link className={cx('empty-cta')} href="/student/projects?from=review">+ Add now</Link>
              </div>
            )}
          </div>
        </div>

        <div className={cx('step-actions')}>
          <Link className={cx('button', 'secondary')} href="/student/projects">Back</Link>
          {submitError && <p className={cx('save-message', 'error')}>{submitError}</p>}
          <button
            className={cx('button', 'primary')}
            type="button"
            disabled={completionPercent < 100 || submitting}
            onClick={submitProfile}
          >
            {submitting ? 'Submitting…' : 'Submit Profile'}
          </button>
        </div>
      </section>
    </div>
  );
}

// frontend/src/app/pages/student-portal/review-profile.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { StudentProfileUiStore } from './student-profile-ui.store';

interface ExamEntry { exam: string; status: string; score: string; expectedScore: string; currentScore: string; }
interface ProjectEntry { title: string; role: string; description: string; }

@Component({
  standalone: true,
  imports: [CommonModule, RouterLink],
  styleUrl: './review-profile.css',
  template: `
    <section class="step-page">
      <div class="step-heading">
        <span>STEP 7 OF 8</span>
        <h1>Review Profile</h1>
        <p>Check everything looks right before submitting your profile to our partner universities, banks and consultants.</p>
      </div>

      <div class="completion-banner">
        <div class="completion-ring" [style.--pct]="completionPct">
          <b>{{completionPct}}%</b>
        </div>
        <div class="completion-copy">
          <span>Profile Completion</span>
          <strong>{{completionPct}}% Complete</strong>
          <p *ngIf="completionPct===100">Every required section is filled in — you're ready to submit.</p>
          <p *ngIf="completionPct<100">Finish the sections below to unlock submission.</p>
          <div class="completion-missing" *ngIf="missingSectionNames().length">
            <span *ngFor="let m of missingSectionNames()">{{m}}</span>
          </div>
        </div>
      </div>

      <div class="section-grid">
        <!-- Personal Information -->
        <div class="section-card" [class.incomplete]="!personalComplete()">
          <div class="section-head">
            <span class="section-icon">PI</span>
            <div class="section-title-block">
              <h2>Personal Information</h2>
              <span class="section-status" [class.ok]="personalComplete()" [class.warn]="!personalComplete()">{{ personalComplete() ? '✓ Complete' : '⚠ Incomplete' }}</span>
            </div>
            <a class="edit-btn" routerLink="/student/personal-information">Edit</a>
          </div>
          <div class="summary-list">
            <div class="summary-item"><span>Full Name</span><strong [class.empty]="!v('fullName')">{{ v('fullName') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Email</span><strong [class.empty]="!v('email')">{{ v('email') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Mobile</span><strong [class.empty]="!v('mobileNumber')">{{ v('phone') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Country</span><strong [class.empty]="!v('country')">{{ v('country') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>City</span><strong [class.empty]="!v('city')">{{ v('city') || 'Not added' }}</strong></div>
          </div>
        </div>

        <!-- Study Preferences -->
        <div class="section-card" [class.incomplete]="!studyComplete()">
          <div class="section-head">
            <span class="section-icon">SP</span>
            <div class="section-title-block">
              <h2>Study Preferences</h2>
              <span class="section-status" [class.ok]="studyComplete()" [class.warn]="!studyComplete()">{{ studyComplete() ? '✓ Complete' : '⚠ Incomplete' }}</span>
            </div>
            <a class="edit-btn" routerLink="/student/study-preferences">Edit</a>
          </div>
          <div class="summary-list">
            <div class="summary-item"><span>Countries</span><strong [class.empty]="!v('countries')">{{ v('countries') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Field of Study</span><strong [class.empty]="!v('fieldOfInterest')">{{ v('fieldOfInterest') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Program</span><strong [class.empty]="!v('studyLevel')">{{ v('studyLevel') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Start Year</span><strong [class.empty]="!v('startYear')">{{ v('startYear') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Preferred Intake</span><strong [class.empty]="!v('intake')">{{ v('intake') || 'Not added' }}</strong></div>
          </div>
        </div>

        <!-- Academic Information -->
        <div class="section-card" [class.incomplete]="!academicComplete()">
          <div class="section-head">
            <span class="section-icon">AC</span>
            <div class="section-title-block">
              <h2>Academic Information</h2>
              <span class="section-status" [class.ok]="academicComplete()" [class.warn]="!academicComplete()">{{ academicComplete() ? '✓ Complete' : '⚠ Incomplete' }}</span>
            </div>
            <a class="edit-btn" routerLink="/student/academic-information">Edit</a>
          </div>
          <div class="summary-list">
            <div class="summary-item"><span>Highest Qualification</span><strong [class.empty]="!v('qualificationLevel')">{{ v('qualificationLevel') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Institution</span><strong [class.empty]="!v('institution')">{{ v('institution') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>CGPA / Percentage</span><strong [class.empty]="!v('score')">{{ v('score') || 'Not added' }}</strong></div>
            <div class="summary-item"><span>Completion Year</span><strong [class.empty]="!v('graduationYear')">{{ v('graduationYear') || 'Not added' }}</strong></div>
          </div>
        </div>

        <!-- English Language Tests -->
        <div class="section-card">
          <div class="section-head">
            <span class="section-icon">EN</span>
            <div class="section-title-block">
              <h2>English Language Tests</h2>
              <span class="section-status ok" *ngIf="englishExams().length">✓ {{englishExams().length}} added</span>
            </div>
            <a class="edit-btn" routerLink="/student/entrance-exams">Edit</a>
          </div>
          <div class="entry-list" *ngIf="englishExams().length">
            <div class="entry-row" *ngFor="let e of englishExams()">
              <div><strong>{{e.exam}}</strong><small>{{e.status}}</small></div>
              <span class="entry-badge">{{ examScoreSummary(e) }}</span>
            </div>
          </div>
          <div class="empty-state" *ngIf="!englishExams().length">
            <span class="empty-icon">📝</span>
            <p>No English test recorded yet.</p>
            <a class="empty-cta" routerLink="/student/entrance-exams">+ Add now</a>
          </div>
        </div>

        <!-- Standardized Tests -->
        <div class="section-card">
          <div class="section-head">
            <span class="section-icon">CE</span>
            <div class="section-title-block">
              <h2>Standardized Tests</h2>
              <span class="section-status ok" *ngIf="competitiveExams().length">✓ {{competitiveExams().length}} added</span>
            </div>
            <a class="edit-btn" routerLink="/student/entrance-exams">Edit</a>
          </div>
          <div class="entry-list" *ngIf="competitiveExams().length">
            <div class="entry-row" *ngFor="let e of competitiveExams()">
              <div><strong>{{e.exam}}</strong><small>{{e.status}}</small></div>
              <span class="entry-badge">{{ examScoreSummary(e) }}</span>
            </div>
          </div>
          <div class="empty-state" *ngIf="!competitiveExams().length">
            <span class="empty-icon">🧮</span>
            <p>No standardized test recorded yet.</p>
            <a class="empty-cta" routerLink="/student/entrance-exams">+ Add now</a>
          </div>
        </div>

        <!-- Projects & Achievements -->
        <div class="section-card">
          <div class="section-head">
            <span class="section-icon">PA</span>
            <div class="section-title-block">
              <h2>Projects &amp; Achievements</h2>
            </div>
            <a class="edit-btn" routerLink="/student/projects">Edit</a>
          </div>
          <div class="entry-list" *ngIf="projects().length">
            <div class="entry-row" *ngFor="let p of projects()">
              <div><strong>{{p.title}}</strong><small>{{p.role}}</small></div>
            </div>
          </div>
          <div class="chip-row" *ngIf="achievements().length">
            <span class="chip" *ngFor="let a of achievements()">{{a}}</span>
          </div>
          <div class="empty-state" *ngIf="!projects().length && !achievements().length">
            <span class="empty-icon">🏆</span>
            <p>No projects or achievements added yet.</p>
            <a class="empty-cta" routerLink="/student/projects">+ Add now</a>
          </div>
        </div>
      </div>

      <div class="step-actions">
        <a class="button secondary" routerLink="/student/projects">Back</a>
        <button class="button primary" type="button" [disabled]="completionPct<100" (click)="submitProfile()">Submit Profile</button>
      </div>
    </section>
  `
})
export class ReviewProfileComponent {
  constructor(public store: StudentProfileUiStore, private router: Router) {}

  v(key: string): string { return this.store.values[key] || ''; }

  private parseJsonArray<T>(key: string): T[] {
    try {
      const parsed = JSON.parse(this.store.values[key] || '[]');
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }

  englishExams(): ExamEntry[] { return this.parseJsonArray<ExamEntry>('englishExams'); }
  competitiveExams(): ExamEntry[] { return this.parseJsonArray<ExamEntry>('competitiveExams'); }
  projects(): ProjectEntry[] { return this.parseJsonArray<ProjectEntry>('projects'); }
  achievements(): string[] { return (this.store.values['achievements'] || '').split(',').map(a => a.trim()).filter(Boolean); }

  examScoreSummary(e: ExamEntry): string {
    if (e.status === 'I have the score') return `Score: ${e.score}`;
    if (e.status === 'Retake') return `Current ${e.currentScore} → Target ${e.expectedScore}`;
    if (e.expectedScore) return `Expected: ${e.expectedScore}`;
    return e.status;
  }

  personalComplete(): boolean {
    return !!(this.v('fullName') && this.v('email') && this.v('mobileNumber') && this.v('country') && this.v('city'));
  }
  studyComplete(): boolean {
    return !!(this.v('countries') && this.v('fieldOfInterest') && this.v('studyLevel') && this.v('startYear') && this.v('intake'));
  }
  academicComplete(): boolean {
    return !!(this.v('qualificationLevel') && this.v('institution') && this.v('score') && this.v('graduationYear'));
  }

  private requiredChecklist(): boolean[] {
    return [
      !!this.v('fullName'), !!this.v('email'), !!this.v('mobileNumber'), !!this.v('country'), !!this.v('city'),
      !!this.v('countries'), !!this.v('fieldOfInterest'), !!this.v('studyLevel'), !!this.v('startYear'), !!this.v('intake'),
      !!this.v('qualificationLevel'), !!this.v('institution'), !!this.v('score'), !!this.v('graduationYear')
    ];
  }

  get completionPct(): number {
    const checklist = this.requiredChecklist();
    const done = checklist.filter(Boolean).length;
    return Math.round((done / checklist.length) * 100);
  }

  missingSectionNames(): string[] {
    const missing: string[] = [];
    if (!this.personalComplete()) missing.push('Personal Information');
    if (!this.studyComplete()) missing.push('Study Preferences');
    if (!this.academicComplete()) missing.push('Academic Information');
    return missing;
  }

  submitProfile() {
    if (this.completionPct < 100) return;
    this.router.navigateByUrl('/student/completion');
  }
}
