// components/student/StudentSettings.tsx
'use client';

import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { authApi } from '@/lib/api/auth-api';
import { classNames } from '@/lib/cx';
import { clearAccessToken, readAccessToken } from '@/lib/storage';
import { offerWalletStore } from '@/lib/stores/offer-wallet.store';
import { studentProfileStore, useStudentProfile } from '@/lib/stores/student-profile.store';
import pageStyles from '@/styles/StudentWorkspacePages.module.css';
import settingsStyles from '@/styles/StudentSettings.module.css';
import { StudentSupportChat, OPEN_SUPPORT_CHAT_EVENT } from './StudentSupportChat';
import { StudentWorkspaceRail } from './StudentWorkspaceRail';

/** The component draws on both its own stylesheet and the shared workspace one. */
const cx = classNames({ ...pageStyles, ...settingsStyles });

const SECTIONS = [
  { id: 'account', label: 'Account', description: 'Email and password', icon: '○' },
  { id: 'preferences', label: 'Notifications & Privacy', description: 'Offers, messages and visibility', icon: '◉' },
  { id: 'help', label: 'Help & support', description: 'FAQs and contact', icon: '?' }
];

const FAQS = [
  { question: 'How do I update my student profile?', answer: 'Open your profile from the navigation rail and choose the section you want to update.' },
  { question: 'Where can I upload missing documents?', answer: 'Open Documents from your dashboard action list or student profile.' },
  { question: 'Who can see my profile?', answer: 'Only authorised universities and funding providers permitted by your discovery settings.' }
];

export function StudentSettings() {
  const profile = useStudentProfile();
  const router = useRouter();

  const [activeSection, setActiveSection] = useState('account');
  const [editingEmail, setEditingEmail] = useState(false);
  const [emailDraft, setEmailDraft] = useState('');
  const [emailError, setEmailError] = useState('');
  const [editingName, setEditingName] = useState(false);
  const [nameDraft, setNameDraft] = useState('');
  const [nameError, setNameError] = useState('');
  const [editingPassword, setEditingPassword] = useState(false);
  const [passwordForm, setPasswordForm] = useState({ current: '', next: '', confirm: '' });
  const [passwordError, setPasswordError] = useState('');
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [flashMessage, setFlashMessage] = useState('');
  const [discoveryFlash, setDiscoveryFlash] = useState('');
  const [saving, setSaving] = useState(false);

  const settings = profile.profile.settings as Record<string, unknown>;
  const email = profile.user?.email || profile.profile.personal['email'] || '';
  const fullName = profile.user?.full_name || profile.profile.personal['fullName'] || '';

  /** Notification toggles default to on until the student turns one off. */
  const flag = (key: string, defaultValue = true) => {
    const raw = settings[key];
    return raw === undefined ? defaultValue : Boolean(raw);
  };

  const passwordChangedLabel = (() => {
    const changedAt = profile.user?.password_changed_at;
    return changedAt ? `Last changed ${new Date(changedAt).toLocaleDateString()}` : 'Never changed';
  })();

  const flash = (message: string) => {
    setFlashMessage(message);
    setTimeout(() => setFlashMessage(''), 3000);
  };

  /** Every toggle is a write to `/students/me/settings`; the server stays the source of truth. */
  const writeSettings = async (payload: Record<string, unknown>) => {
    const token = readAccessToken();
    if (!token) {
      router.push('/auth/login/student');
      return;
    }
    await authApi.saveStudentSettings(token, payload);
    await profile.refresh();
  };

  const setPreference = (key: string, value: boolean) => void writeSettings({ [key]: value });

  const setDiscoverable = async (value: boolean) => {
    await writeSettings({ discoverable: value });
    setDiscoveryFlash(
      value
        ? 'Your profile is visible to universities and lenders again.'
        : 'Your profile is hidden from university and lender discovery.'
    );
    setTimeout(() => setDiscoveryFlash(''), 3500);
  };

  const saveEmail = async () => {
    const value = emailDraft.trim();
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
      setEmailError('Enter a valid email address');
      return;
    }
    const token = readAccessToken();
    if (!token) return;

    setSaving(true);
    try {
      await authApi.updateAccount(token, { email: value });
      await profile.refresh();
      setEditingEmail(false);
      flash('Email address updated.');
    } catch (e) {
      setEmailError(e instanceof Error ? e.message : 'That email could not be saved.');
    } finally {
      setSaving(false);
    }
  };

  const saveName = async () => {
    const value = nameDraft.trim();
    if (value.length < 2) {
      setNameError('Enter your full name');
      return;
    }
    const token = readAccessToken();
    if (!token) return;

    setSaving(true);
    try {
      await authApi.updateAccount(token, { fullName: value });
      await profile.refresh();
      setEditingName(false);
      flash('Full name updated.');
    } catch (e) {
      setNameError(e instanceof Error ? e.message : 'That name could not be saved.');
    } finally {
      setSaving(false);
    }
  };

  const cancelPassword = () => {
    setEditingPassword(false);
    setPasswordForm({ current: '', next: '', confirm: '' });
    setPasswordError('');
  };

  /** The server revokes every other session on success, so this one keeps its token and the rest are cut. */
  const savePassword = async () => {
    const { current, next, confirm } = passwordForm;
    if (!current.trim()) { setPasswordError('Enter your current password'); return; }
    if (next.length < 8) { setPasswordError('New password must be at least 8 characters'); return; }
    if (next !== confirm) { setPasswordError('New password and confirmation do not match'); return; }

    const token = readAccessToken();
    if (!token) return;

    setSaving(true);
    try {
      await authApi.changePassword(token, current, next);
      await profile.refresh();
      cancelPassword();
      flash('Password updated.');
    } catch (e) {
      setPasswordError(e instanceof Error ? e.message : 'Your password could not be changed.');
    } finally {
      setSaving(false);
    }
  };

  const deleteAccount = async () => {
    const token = readAccessToken();
    if (!token) return;

    setSaving(true);
    try {
      await authApi.deleteStudentAccount(token);
    } finally {
      setSaving(false);
      clearAccessToken();
      studentProfileStore.reset();
      offerWalletStore.reset();
      setConfirmingDelete(false);
      router.push('/');
    }
  };

  const openChat = () => window.dispatchEvent(new CustomEvent(OPEN_SUPPORT_CHAT_EVENT));

  return (
    <div className={cx('host')}>
      <StudentWorkspaceRail />
      <main className={cx('professional-settings')}>
        <header className={cx('settings-page-header')}>
          <div><span>SETTINGS</span><h1>Account settings</h1><p>Manage your account and preferences.</p></div>
        </header>

        <div className={cx('settings-shell')}>
          <nav className={cx('settings-menu')} aria-label="Settings sections">
            {SECTIONS.map(item => (
              <button
                key={item.id}
                type="button"
                className={cx(activeSection === item.id && 'active')}
                onClick={() => setActiveSection(item.id)}
              >
                <span>{item.icon}</span>
                <div><strong>{item.label}</strong><small>{item.description}</small></div>
                <b>›</b>
              </button>
            ))}
          </nav>

          {activeSection === 'account' && (
            <section className={cx('settings-panel')}>
              <header><h2>Account</h2><p>Your sign-in details and account access.</p></header>
              {flashMessage && <p className={cx('settings-flash')}>{flashMessage}</p>}

              {!editingEmail && (
                <div className={cx('professional-setting-row')}>
                  <div><strong>Email address</strong><small>{email || 'Not set'}</small></div>
                  <button type="button" onClick={() => { setEmailDraft(email); setEmailError(''); setEditingEmail(true); }}>
                    Edit
                  </button>
                </div>
              )}
              {editingEmail && (
                <div className={cx('professional-setting-row')}>
                  <div style={{ flex: 1 }}>
                    <strong>Email address</strong>
                    <div className={cx('inline-edit')} style={{ marginTop: 6 }}>
                      <input
                        type="email" value={emailDraft} placeholder="you@example.com" autoComplete="email"
                        onChange={event => setEmailDraft(event.target.value)}
                      />
                      <button type="button" disabled={saving} onClick={() => void saveEmail()}>Save</button>
                      <button type="button" onClick={() => setEditingEmail(false)}>Cancel</button>
                    </div>
                    {emailError && <p className={cx('field-error')}>{emailError}</p>}
                  </div>
                </div>
              )}

              {!editingPassword && (
                <div className={cx('professional-setting-row')}>
                  <div><strong>Password</strong><small>{passwordChangedLabel}</small></div>
                  <button type="button" onClick={() => setEditingPassword(true)}>Change password</button>
                </div>
              )}
              {editingPassword && (
                <form className={cx('password-form')} onSubmit={event => { event.preventDefault(); void savePassword(); }}>
                  <input
                    type="password" name="currentPassword" placeholder="Current password" autoComplete="current-password"
                    value={passwordForm.current}
                    onChange={event => setPasswordForm(current => ({ ...current, current: event.target.value }))}
                  />
                  <input
                    type="password" name="newPassword" placeholder="New password (min. 8 characters)" autoComplete="new-password"
                    value={passwordForm.next}
                    onChange={event => setPasswordForm(current => ({ ...current, next: event.target.value }))}
                  />
                  <input
                    type="password" name="confirmPassword" placeholder="Confirm new password" autoComplete="new-password"
                    value={passwordForm.confirm}
                    onChange={event => setPasswordForm(current => ({ ...current, confirm: event.target.value }))}
                  />
                  {passwordError && <p className={cx('field-error')}>{passwordError}</p>}
                  <div className={cx('password-actions')}>
                    <button type="submit" disabled={saving}>Update password</button>
                    <button type="button" onClick={cancelPassword}>Cancel</button>
                  </div>
                </form>
              )}

              {!editingName && (
                <div className={cx('professional-setting-row')}>
                  <div><strong>Full name</strong><small>{fullName || 'Not set'}</small></div>
                  <button type="button" onClick={() => { setNameDraft(fullName); setNameError(''); setEditingName(true); }}>
                    Edit profile
                  </button>
                </div>
              )}
              {editingName && (
                <div className={cx('professional-setting-row')}>
                  <div style={{ flex: 1 }}>
                    <strong>Full name</strong>
                    <div className={cx('inline-edit')} style={{ marginTop: 6 }}>
                      <input
                        type="text" value={nameDraft} placeholder="Your full name" autoComplete="name"
                        onChange={event => setNameDraft(event.target.value)}
                      />
                      <button type="button" disabled={saving} onClick={() => void saveName()}>Save</button>
                      <button type="button" onClick={() => setEditingName(false)}>Cancel</button>
                    </div>
                    {nameError && <p className={cx('field-error')}>{nameError}</p>}
                  </div>
                </div>
              )}

              {!confirmingDelete && (
                <div className={cx('settings-danger-row')}>
                  <div><strong>Delete account</strong><small>Permanently delete your account and student profile.</small></div>
                  <button type="button" onClick={() => setConfirmingDelete(true)}>Delete account</button>
                </div>
              )}
              {confirmingDelete && (
                <div className={cx('danger-confirm')}>
                  <p>
                    <strong>This can&apos;t be undone.</strong> Your profile, submitted applications, and offers will be
                    permanently deleted.
                  </p>
                  <div className={cx('password-actions')}>
                    <button type="button" disabled={saving} onClick={() => void deleteAccount()}>Yes, delete my account</button>
                    <button type="button" onClick={() => setConfirmingDelete(false)}>Cancel</button>
                  </div>
                </div>
              )}
            </section>
          )}

          {activeSection === 'preferences' && (
            <section className={cx('settings-panel')}>
              <header><h2>Notifications &amp; Privacy</h2><p>Choose what you hear about and who can find your profile.</p></header>
              <label className={cx('toggle-row')}>
                <div><strong>University offers</strong><small>Admission and scholarship opportunities</small></div>
                <input
                  className={cx('mini-toggle')} type="checkbox" checked={flag('notifyUniversity')}
                  onChange={event => setPreference('notifyUniversity', event.target.checked)}
                />
              </label>
              <label className={cx('toggle-row')}>
                <div><strong>Funding offers</strong><small>Education loan and finance opportunities</small></div>
                <input
                  className={cx('mini-toggle')} type="checkbox" checked={flag('notifyLoan')}
                  onChange={event => setPreference('notifyLoan', event.target.checked)}
                />
              </label>
              <label className={cx('toggle-row')}>
                <div><strong>Messages</strong><small>Replies from universities and finance advisers</small></div>
                <input
                  className={cx('mini-toggle')} type="checkbox" checked={flag('notifyMessages')}
                  onChange={event => setPreference('notifyMessages', event.target.checked)}
                />
              </label>
              <label className={cx('toggle-row')}>
                <div>
                  <strong>Profile discovery</strong>
                  <small>Allow verified universities and funding providers to discover your profile.</small>
                </div>
                <input
                  className={cx('mini-toggle')} type="checkbox" checked={profile.profile.discoverable}
                  onChange={event => void setDiscoverable(event.target.checked)}
                />
              </label>
              {discoveryFlash && <p className={cx('settings-flash')}>{discoveryFlash}</p>}
              <div className={cx('settings-note')}>
                <span>i</span>
                <p>
                  Your contact details are never displayed publicly. Only authorised partners can access information
                  permitted by your visibility settings.
                </p>
              </div>
            </section>
          )}

          {activeSection === 'help' && (
            <section className={cx('settings-panel')}>
              <header><h2>Help &amp; support</h2><p>Find answers or contact the SuperOffer team.</p></header>
              <a className={cx('support-setting-row')} href="mailto:support@superoffer.net">
                <span>✉</span><div><strong>Email support</strong><small>support@superoffer.net</small></div><b>›</b>
              </a>
              <button className={cx('support-setting-row')} type="button" onClick={openChat}>
                <span>◌</span><div><strong>Chat with us</strong><small>Start a conversation with support</small></div><b>›</b>
              </button>
              {FAQS.map(item => (
                <details key={item.question}>
                  <summary>{item.question}<b>＋</b></summary>
                  <p>{item.answer}</p>
                </details>
              ))}
            </section>
          )}
        </div>
      </main>
      <StudentSupportChat />
    </div>
  );
}

// src/app/pages/student-portal/student-settings.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { StudentProfileUiStore } from './student-profile-ui.store';
import { StudentWorkspaceRailComponent } from './student-workspace-rail.component';
import { StudentSupportChatComponent } from './student-support-chat.component';

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule, StudentWorkspaceRailComponent, StudentSupportChatComponent],
  styleUrl: './student-workspace-pages.css',
  template: `
    <app-student-workspace-rail />
    <main class="professional-settings">
      <header class="settings-page-header">
        <div><span>SETTINGS</span><h1>Account settings</h1><p>Manage your account and preferences.</p></div>
      </header>

      <div class="settings-shell">
        <nav class="settings-menu" aria-label="Settings sections">
          <button *ngFor="let item of sections" type="button" [class.active]="activeSection===item.id" (click)="activeSection=item.id">
            <span>{{item.icon}}</span>
            <div><strong>{{item.label}}</strong><small>{{item.description}}</small></div>
            <b>›</b>
          </button>
        </nav>

        <section class="settings-panel" *ngIf="activeSection==='account'">
          <header><h2>Account</h2><p>Your sign-in details and account access.</p></header>
          <div class="professional-setting-row">
            <div><strong>Email address</strong><small>{{store.values['email'] || 'aarav@example.com'}}</small></div>
            <button type="button">Edit</button>
          </div>
          <div class="professional-setting-row">
            <div><strong>Password</strong><small>Last changed recently</small></div>
            <button type="button">Change password</button>
          </div>
          <div class="professional-setting-row">
            <div><strong>Full name</strong><small>{{store.values['fullName'] || 'Aarav Mehta'}}</small></div>
            <button type="button">Edit profile</button>
          </div>
          <div class="settings-danger-row">
            <div><strong>Delete account</strong><small>Permanently delete your account and student profile.</small></div>
            <button type="button">Delete account</button>
          </div>
        </section>

        <section class="settings-panel" *ngIf="activeSection==='notifications'">
          <header><h2>Notifications</h2><p>Choose which updates you want to receive.</p></header>
          <label class="professional-setting-row">
            <div><strong>University offers</strong><small>Admission and scholarship opportunities</small></div>
            <input class="settings-toggle" type="checkbox" [(ngModel)]="universityUpdates">
          </label>
          <label class="professional-setting-row">
            <div><strong>Funding offers</strong><small>Education loan and finance opportunities</small></div>
            <input class="settings-toggle" type="checkbox" [(ngModel)]="loanUpdates">
          </label>
          <label class="professional-setting-row">
            <div><strong>Messages</strong><small>Replies from universities and finance advisers</small></div>
            <input class="settings-toggle" type="checkbox" [(ngModel)]="messageUpdates">
          </label>
        </section>

        <section class="settings-panel" *ngIf="activeSection==='privacy'">
          <header><h2>Privacy</h2><p>Control how your profile is used for opportunity matching.</p></header>
          <label class="professional-setting-row">
            <div><strong>Profile discovery</strong><small>Allow verified universities and funding providers to discover your profile.</small></div>
            <input class="settings-toggle" type="checkbox" [(ngModel)]="discoverable">
          </label>
          <div class="settings-note"><span>i</span><p>Your contact details are never displayed publicly. Only authorised partners can access information permitted by your visibility settings.</p></div>
        </section>

        <section class="settings-panel" *ngIf="activeSection==='help'">
          <header><h2>Help & support</h2><p>Find answers or contact the SuperOffer team.</p></header>
          <a class="support-setting-row" href="mailto:support@superoffer.net"><span>✉</span><div><strong>Email support</strong><small>support@superoffer.net</small></div><b>›</b></a>
          <button class="support-setting-row" type="button" (click)="openChat()"><span>◌</span><div><strong>Chat with us</strong><small>Start a conversation with support</small></div><b>›</b></button>
          <details *ngFor="let item of faqs"><summary>{{item.question}}<b>＋</b></summary><p>{{item.answer}}</p></details>
        </section>
      </div>
    </main>
    <app-student-support-chat />
  `
})
export class StudentSettingsComponent {
  activeSection = 'account';
  universityUpdates = true;
  loanUpdates = true;
  messageUpdates = true;
  discoverable = true;
  sections = [
    {id:'account',label:'Account',description:'Email and password',icon:'○'},
    {id:'notifications',label:'Notifications',description:'Offers and messages',icon:'◉'},
    {id:'privacy',label:'Privacy',description:'Profile visibility',icon:'◇'},
    {id:'help',label:'Help & support',description:'FAQs and contact',icon:'?'}
  ];
  faqs = [
    {question:'How do I update my student profile?',answer:'Open your profile from the navigation rail and choose the section you want to update.'},
    {question:'Where can I upload missing documents?',answer:'Open Documents from your dashboard action list or student profile.'},
    {question:'Who can see my profile?',answer:'Only authorised universities and funding providers permitted by your discovery settings.'}
  ];
  constructor(public store: StudentProfileUiStore) {}
  openChat(){window.dispatchEvent(new CustomEvent('open-student-support-chat'));}
}
