// components/student/StudentFullProfile.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { authApi } from '@/lib/api/auth-api';
import { classNames } from '@/lib/cx';
import { clearAccessToken, readAccessToken } from '@/lib/storage';
import { offerWalletStore } from '@/lib/stores/offer-wallet.store';
import { studentProfileStore, useStudentProfile } from '@/lib/stores/student-profile.store';
import styles from '@/styles/StudentFullProfile.module.css';
import { StudentWorkspaceShell } from './StudentWorkspaceShell';

const cx = classNames(styles);

export function StudentFullProfile() {
  const profile = useStudentProfile();
  const router = useRouter();
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  /** The checklist comes from `/reference/documents`; each row is a `documentType`. */
  const [documentTypes, setDocumentTypes] = useState<string[]>([]);

  useEffect(() => {
    void authApi
      .getDocumentReferenceData()
      .then(reference => setDocumentTypes(reference.profileDocumentTypes))
      .catch(() => setDocumentTypes([]));
  }, []);

  const { personal, studyPreferences, academic, projects, documents } = profile.profile;

  const list = (value?: string[]) => (value || []).join(', ');

  const sections = [
    {
      eyebrow: 'PERSONAL', title: 'Personal information', route: '/student/personal-information',
      items: [
        { label: 'Email', value: personal['email'] },
        { label: 'Phone', value: personal['phone'] || personal['mobileNumber'] },
        { label: 'Location', value: personal['location'] }
      ]
    },
    {
      eyebrow: 'ACADEMIC', title: 'Academic information', route: '/student/academic-information',
      items: [
        { label: 'Institution', value: academic['institution'] as string },
        { label: 'Qualification', value: academic['qualification'] as string },
        { label: 'Academic score', value: academic['score'] as string }
      ]
    },
    {
      eyebrow: 'PREFERENCES', title: 'Study preferences', route: '/student/study-preferences',
      items: [
        { label: 'Field', value: list(studyPreferences['fieldOfInterest']) },
        { label: 'Countries', value: list(studyPreferences['countries']) },
        { label: 'Intake', value: list(studyPreferences['intake']) }
      ]
    },
    {
      eyebrow: 'PROFILE', title: 'Skills and achievements', route: '/student/projects',
      items: [
        { label: 'Achievements', value: ((projects['achievements'] as string[]) || []).join(', ') },
        { label: 'Links', value: ((projects['links'] as string[]) || []).join(', ') },
        { label: 'Featured project', value: projects['projectTitle'] as string }
      ]
    }
  ];

  const documentFor = (type: string) => documents.find(document => document.documentType === type);

  /** Uploads replace any existing file of the same type, so the checklist stays one-per-row. */
  const upload = async (documentType: string, file?: File) => {
    if (!file) return;
    const token = readAccessToken();
    if (!token) {
      router.push('/auth/login/student');
      return;
    }

    setBusy(documentType);
    setError('');
    try {
      const existing = documentFor(documentType);
      if (existing) await authApi.replaceStudentDocument(token, existing.id, file);
      else await authApi.uploadStudentDocument(token, documentType, file);
      await profile.refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'That file could not be uploaded.');
    } finally {
      setBusy('');
    }
  };

  const remove = async (documentType: string) => {
    const existing = documentFor(documentType);
    const token = readAccessToken();
    if (!existing || !token) return;

    setBusy(documentType);
    setError('');
    try {
      await authApi.deleteStudentDocument(token, existing.id);
      await profile.refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'That file could not be removed.');
    } finally {
      setBusy('');
    }
  };

  /** Ends the session on the server too, so the token cannot be reused. */
  const logout = async () => {
    const token = readAccessToken();
    if (token) await authApi.logout(token).catch(() => {});
    clearAccessToken();
    studentProfileStore.reset();
    offerWalletStore.reset();
    router.push('/');
  };

  return (
    <StudentWorkspaceShell layout="workspace" backdrop="canvas">
      <main className={cx('full-profile-page')}>
        <header className={cx('profile-top')}>
          <Link href="/student/offers">← Back to offers</Link>
          <button type="button" onClick={() => void logout()}>Logout</button>
        </header>

        <section className={cx('profile-hero')}>
          <div className={cx('large-avatar')}><span>{profile.initials}</span></div>
          <div>
            <small>STUDENT PROFILE</small>
            <h1>{profile.fullName}</h1>
            <p>
              {(academic['qualification'] as string) || 'Qualification'} · {personal['location'] || 'Location'}
            </p>
          </div>
          <span className={cx('completion-badge')}>{profile.completion.completionPercent}% complete</span>
        </section>

        <div className={cx('profile-layout')}>
          <section className={cx('profile-sections')}>
            {sections.map(section => (
              <article key={section.title}>
                <div><small>{section.eyebrow}</small><h2>{section.title}</h2></div>
                <dl>
                  {section.items.map(item => (
                    <div key={item.label} style={{ display: 'contents' }}>
                      <dt>{item.label}</dt>
                      <dd>{item.value || 'Not added'}</dd>
                    </div>
                  ))}
                </dl>
                <Link href={section.route}>Edit section</Link>
              </article>
            ))}
          </section>

          <aside className={cx('documents-panel')}>
            <span>DOCUMENT CHECKLIST</span>
            <h2>Complete your documents</h2>
            <p>Files are uploaded to your profile and visible only to you and SuperOffer.</p>
            {error && <p className={cx('field-error')}>{error}</p>}
            {documentTypes.map(documentType => {
              const uploaded = documentFor(documentType);
              return (
                <label key={documentType} className={cx(uploaded && 'complete')}>
                  <div>
                    <strong>{documentType}</strong>
                    <small>{busy === documentType ? 'Uploading…' : uploaded?.fileName || 'Not uploaded'}</small>
                  </div>
                  {uploaded ? (
                    <b
                      onClick={event => {
                        event.preventDefault();
                        void remove(documentType);
                      }}
                      title="Remove this file"
                    >
                      ✓
                    </b>
                  ) : (
                    <b>＋</b>
                  )}
                  <input
                    type="file"
                    accept=".pdf,.jpg,.jpeg,.png"
                    onChange={event => void upload(documentType, event.target.files?.[0])}
                  />
                </label>
              );
            })}
            <Link href="/student/review">Open review step</Link>
          </aside>
        </div>
      </main>
    </StudentWorkspaceShell>
  );
}

// src/app/pages/student-portal/student-full-profile.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { StudentProfileUiStore } from './student-profile-ui.store';
import { StudentWorkspaceRailComponent } from './student-workspace-rail.component';

@Component({
  standalone: true,
  imports: [CommonModule, RouterLink, StudentWorkspaceRailComponent],
  styleUrl: './student-full-profile.css',
  template: `
    <app-student-workspace-rail />
    <main class="full-profile-page">
      <header class="profile-top">
        <a routerLink="/student/offers">← Back to offers</a>
        <button type="button" (click)="logout()">Logout</button>
      </header>

      <section class="profile-hero">
        <div class="large-avatar">
          <img *ngIf="store.photo" [src]="store.photo" alt="Student profile photo">
          <span *ngIf="!store.photo">{{initials}}</span>
        </div>
        <div><small>STUDENT PROFILE</small><h1>{{store.values['fullName'] || 'Student Name'}}</h1><p>{{store.values['qualification'] || 'Qualification'}} · {{store.values['location'] || 'Location'}}</p></div>
        <span class="completion-badge">Profile preview</span>
      </section>

      <div class="profile-layout">
        <section class="profile-sections">
          <article *ngFor="let section of sections">
            <div><small>{{section.eyebrow}}</small><h2>{{section.title}}</h2></div>
            <dl><ng-container *ngFor="let item of section.items"><dt>{{item.label}}</dt><dd>{{value(item.key,item.fallback)}}</dd></ng-container></dl>
            <a [routerLink]="section.route">Edit section</a>
          </article>
        </section>

        <aside class="documents-panel">
          <span>DOCUMENT CHECKLIST</span><h2>Complete your documents</h2><p>Add any missing files while reviewing your profile.</p>
          <label *ngFor="let doc of documents" [class.complete]="store.values[doc.key]">
            <div><strong>{{doc.label}}</strong><small>{{store.values[doc.key] || 'Not uploaded'}}</small></div>
            <b>{{store.values[doc.key]?'✓':'＋'}}</b>
            <input type="file" (change)="chooseFile(doc.key,$event)">
          </label>
          <a routerLink="/student/documents">Open documents step</a>
        </aside>
      </div>
    </main>
  `
})
export class StudentFullProfileComponent {
  sections = [
    { eyebrow:'PERSONAL',title:'Personal information',route:'/student/personal-information',items:[{label:'Email',key:'email',fallback:'aarav@example.com'},{label:'Phone',key:'phone',fallback:'+91 98765 43210'},{label:'Location',key:'location',fallback:'Bengaluru, India'}]},
    { eyebrow:'ACADEMIC',title:'Academic information',route:'/student/academic-information',items:[{label:'Institution',key:'institution',fallback:'Current institution'},{label:'Qualification',key:'qualification',fallback:'B.Tech Computer Science'},{label:'Academic score',key:'score',fallback:'8.7 / 10'}]},
    { eyebrow:'PREFERENCES',title:'Study preferences',route:'/student/study-preferences',items:[{label:'Field',key:'fieldOfInterest',fallback:'Data Science'},{label:'Countries',key:'countries',fallback:'Canada, United Kingdom'},{label:'Intake',key:'intake',fallback:'Fall 2027'}]},
    { eyebrow:'PROFILE',title:'Skills and achievements',route:'/student/projects',items:[{label:'Skills',key:'technicalSkills',fallback:'Python, SQL, Machine Learning'},{label:'Languages',key:'languages',fallback:'English, Hindi'},{label:'Featured project',key:'projectTitle',fallback:'Student success prediction model'}]}
  ];
  documents=[{key:'transcript',label:'Academic transcript'},{key:'resume',label:'CV / résumé'},{key:'passport',label:'Passport copy'},{key:'testReport',label:'Test score report'}];
  constructor(public store:StudentProfileUiStore,private router:Router){}
  get initials(){return (this.store.values['fullName']||'Student').split(' ').map(value=>value[0]).join('').slice(0,2).toUpperCase();}
  value(key:string,fallback:string){return this.store.values[key]||fallback;}
  chooseFile(key:string,event:Event){this.store.setFile(key,(event.target as HTMLInputElement).files?.[0]);}
  logout(){localStorage.removeItem('superoffer_access_token');sessionStorage.removeItem('superoffer_access_token');this.router.navigate(['/']);}
}
