// components/student/WorkExperience.tsx
'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { authApi, type ApiError } from '@/lib/api/auth-api';
import { useSectionFields } from '@/lib/forms/use-section-fields';
import { classNames } from '@/lib/cx';
import { clearAccessToken, readAccessToken } from '@/lib/storage';
import { useCompositeRows } from '@/lib/forms/use-composite-rows';
import { useSchemaExtras } from '@/lib/forms/use-schema-extras';
import { useStudentProfile } from '@/lib/stores/student-profile.store';
import styles from '@/styles/WorkExperience.module.css';
import { SchemaFields } from './SchemaFields';

const cx = classNames(styles);

interface Experience {
  companyName: string;
  role: string;
  type: string;
  durationMonths: string;
  description: string;
}

const emptyExperience = (entry?: Record<string, string>): Experience => ({
  companyName: entry?.['companyName'] || '',
  role: entry?.['role'] || '',
  type: entry?.['type'] || '',
  durationMonths: entry?.['durationMonths'] || '',
  description: entry?.['description'] || ''
});

export function WorkExperience() {
  const profile = useStudentProfile();
  const router = useRouter();
  const searchParams = useSearchParams();
  const returnToReview = searchParams.get('from') === 'review';

  const [employmentTypes, setEmploymentTypes] = useState<string[]>([]);
  const [workStatus, setWorkStatus] = useState('');
  const [relevantYears, setRelevantYears] = useState('');
  const [nonRelevantYears, setNonRelevantYears] = useState('');
  const [experiences, setExperiences] = useState<Experience[]>([]);
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [submitted, setSubmitted] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');
  const seeded = useRef(false);

  /** Fields this step draws by hand; anything else the schema declares is added below. */
  /** What the published form says about the fields drawn by hand below. */
  const fields = useSectionFields('workExperience', ['workStatus', 'relevantYears', 'nonRelevantYears', 'experiences']);

  /** What each role row asks for, as published. */
  const rows = useCompositeRows('workExperience', 'experiences');

  const extras = useSchemaExtras(
    'workExperience',
    ['workStatus', 'relevantYears', 'nonRelevantYears', 'experiences', 'companyName', 'jobRole'],
    profile.profile.workExperience,
    profile.loaded
  );


  const handleUnauthorized = () => {
    clearAccessToken();
    router.push('/auth/login/student?sessionExpired=1');
  };

  /** Seed once from the section the server already holds. */
  useEffect(() => {
    if (seeded.current || !profile.loaded) return;
    seeded.current = true;
    const work = profile.profile.workExperience || {};
    const status = String(work['workStatus'] || '');
    setWorkStatus(status);
    setRelevantYears(String(work['relevantYears'] || ''));
    setNonRelevantYears(String(work['nonRelevantYears'] || ''));
    if (status === 'Yes') {
      const saved = (work['experiences'] as Record<string, string>[]) || [];
      setExperiences(saved.length ? saved.map(emptyExperience) : [emptyExperience()]);
    }
  }, [profile.loaded, profile.profile.workExperience]);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      const token = readAccessToken();
      if (!token) {
        router.push('/auth/login/student');
        return;
      }
      try {
        const options = await authApi.getWorkExperienceReferenceData();
        if (!cancelled) setEmploymentTypes(options.employmentTypes);
      } catch {
        // Reference data endpoint unreachable — the type dropdown stays empty.
      }
    })();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onWorkStatusChange = (value: string) => {
    setWorkStatus(value);
    setTouched(current => ({ ...current, workStatus: true }));
    if (value === 'Yes') {
      setExperiences(current => (current.length ? current : [emptyExperience()]));
    } else {
      setExperiences([]);
      setRelevantYears('');
      setNonRelevantYears('');
      setTouched(current => ({ ...current, relevantYears: false, nonRelevantYears: false }));
    }
  };

  const addExperience = () => setExperiences(current => [...current, emptyExperience()]);
  const removeExperience = (index: number) => setExperiences(current => current.filter((_, i) => i !== index));
  const setExperienceValue = (index: number, key: keyof Experience, value: string) =>
    setExperiences(current => current.map((entry, i) => (i === index ? { ...entry, [key]: value } : entry)));

  const markTouched = (key: string) => setTouched(current => ({ ...current, [key]: true }));

  const yearsRequired = workStatus === 'Yes';
  /** A field the admin has hidden or relaxed cannot block the step. */
  const fieldInvalid = (key: 'relevantYears' | 'nonRelevantYears') => {
    if (!fields.shows(key) || !fields.isRequired(key, true)) return false;
    return yearsRequired && !(key === 'relevantYears' ? relevantYears : nonRelevantYears).trim();
  };
  const showError = (key: 'relevantYears' | 'nonRelevantYears') => (touched[key] || submitted) && fieldInvalid(key);

  /**
   * Which fields a role must carry comes from the published row definition, so an
   * admin making one optional actually makes it optional.
   */
  const rowErrors = (index: number, entry: Experience) => {
    const errors: Record<string, string> = {};
    for (const key of rows.missingIn(entry as unknown as Record<string, unknown>)) {
      errors[key] = `${rows.all.find(field => field.key === key)?.label || key} is required`;
    }
    void index;
    return errors;
  };

  const rowTouched = (index: number) => {
    const marks: Record<string, boolean> = {};
    for (const field of rows.all) marks[field.key] = touched[`exp.${index}.${field.key}`] || submitted;
    return marks;
  };

  const formInvalid =
    fieldInvalid('relevantYears') ||
    fieldInvalid('nonRelevantYears') ||
    experiences.some(entry => !!rows.missingIn(entry as unknown as Record<string, unknown>).length);

  const saveAndContinue = async () => {
    setSubmitted(true);
    extras.touchAll();
    setSaveError('');
    if (formInvalid) return;

    const token = readAccessToken();
    if (!token) {
      router.push('/auth/login/student');
      return;
    }

    const first = experiences[0];
    const companyName = first ? first.companyName : '';
    const jobRole = first ? first.role : '';

    setSaving(true);
    try {
      await authApi.saveStudentWorkExperience(token, {
        ...extras.values0,
        workStatus: workStatus || undefined,
        relevantYears: relevantYears || undefined,
        nonRelevantYears: nonRelevantYears || undefined,
        experiences,
        companyName,
        jobRole
      });

      await profile.refresh();

      router.push(returnToReview ? '/student/review' : '/student/financial-information');
    } catch (e) {
      if ((e as ApiError).status === 401) {
        handleUnauthorized();
        return;
      }
      setSaveError(e instanceof Error ? e.message : 'Could not save your work experience. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className={cx('host')}>
      <section className={cx('step-page')}>
        <form className={cx('profile-form-card')} onSubmit={event => { event.preventDefault(); void saveAndContinue(); }}>
          {!!extras.fields.length && (
            <SchemaFields
              fields={extras.fields}
              values={extras.values}
              errors={extras.errors}
              touched={extras.touched}
              cx={cx}
              onChange={extras.setValue}
              onBlur={extras.setTouched}
            />
          )}


          <div className={cx('card-head')}>
            <div className={cx('placeholder-copy')}>
              <div>
                <h2>Work Experience details</h2>
                <p>Your information is securely saved to your student profile.</p>
              </div>
            </div>
            <span className={cx('step-badge')}>STEP 6 OF 9</span>
          </div>

          <h3 className={cx('section-title')}>Do you have any work experience?</h3>
          <div className={cx('toggle-group')}>
            <label className={cx('toggle-option', workStatus === 'Fresher' && 'active')}>
              <input
                type="radio" name="workStatus" value="Fresher"
                checked={workStatus === 'Fresher'}
                onChange={() => onWorkStatusChange('Fresher')}
              /> I am a Fresher
            </label>
            <label className={cx('toggle-option', workStatus === 'Yes' && 'active')}>
              <input
                type="radio" name="workStatus" value="Yes"
                checked={workStatus === 'Yes'}
                onChange={() => onWorkStatusChange('Yes')}
              /> Yes
            </label>
          </div>

          <div className={cx('reveal-section', workStatus === 'Yes' && 'open')}>
            <div className={cx('dynamic-fields')}>
              {fields.shows('relevantYears') && (
                <label className={cx(showError('relevantYears') && 'field-invalid')}>
                  <span className={cx('field-label')}>{fields.labelOf('relevantYears', 'Relevant Experience (Years)')}{fields.isRequired('relevantYears', true) && <span className={cx('required-mark')}> *</span>}</span>
                  <input
                    type="number" min="0" placeholder="e.g. 2"
                    value={relevantYears}
                    onChange={event => setRelevantYears(event.target.value)}
                    onBlur={() => markTouched('relevantYears')}
                  />
                  {showError('relevantYears') && <small className={cx('field-error')}>Enter your relevant experience</small>}
                </label>
              )}
              {fields.shows('nonRelevantYears') && (
                <label className={cx(showError('nonRelevantYears') && 'field-invalid')}>
                  <span className={cx('field-label')}>{fields.labelOf('nonRelevantYears', 'Non-Relevant Experience (Years)')}{fields.isRequired('nonRelevantYears', true) && <span className={cx('required-mark')}> *</span>}</span>
                  <input
                    type="number" min="0" placeholder="e.g. 1"
                    value={nonRelevantYears}
                    onChange={event => setNonRelevantYears(event.target.value)}
                    onBlur={() => markTouched('nonRelevantYears')}
                  />
                  {showError('nonRelevantYears') && <small className={cx('field-error')}>Enter your non-relevant experience</small>}
                </label>
              )}
            </div>

            <h3 className={cx('section-title')}>Experience details</h3>
            <p className={cx('section-hint')}>Add each job or internship — company, role and how long you were there.</p>

            {experiences.map((entry, index) => (
              <div key={index} className={cx('experience-entry')}>
                <div className={cx('experience-entry-head')}>
                  <strong>Experience {index + 1}</strong>
                  <button
                    type="button" className={cx('experience-remove')}
                    onClick={() => removeExperience(index)}
                    aria-label="Remove experience"
                  >
                    ×
                  </button>
                </div>
                {/* The row asks for whatever the published definition says it does. */}
                <div className={cx('dynamic-fields')}>
                  <SchemaFields
                    fields={rows.all}
                    values={entry as unknown as Record<string, unknown>}
                    errors={rowErrors(index, entry)}
                    touched={rowTouched(index)}
                    cx={cx}
                    onChange={(key, value) => setExperienceValue(index, key as keyof Experience, String(value ?? ''))}
                    onBlur={key => markTouched(`exp.${index}.${key}`)}
                  />
                </div>
              </div>
            ))}

            <button type="button" className={cx('add-experience-btn')} onClick={addExperience}>
              + Add {experiences.length ? 'another' : 'an'} experience
            </button>
          </div>

          {submitted && formInvalid && (
            <p className={cx('save-message', 'error')}>Please fix the highlighted fields before continuing.</p>
          )}
          {saveError && <p className={cx('save-message', 'error')}>{saveError}</p>}
        </form>

        <div className={cx('step-actions')}>
          <Link className={cx('button', 'secondary')} href="/student/competitive-exam">Previous</Link>
          <button className={cx('button', 'primary')} type="button" disabled={saving} onClick={saveAndContinue}>
            {saving ? 'Saving…' : 'Continue'}
          </button>
        </div>
      </section>
    </div>
  );
}

// src/app/pages/student-portal/work-experience.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { AbstractControl, FormArray, FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { StudentProfileUiStore } from './student-profile-ui.store';
import { AuthApiService } from '../../core/auth-api.service';

@Component({
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  styleUrl: './work-experience.css',
  template: `
    <section class="step-page">
      <form class="profile-form-card" [formGroup]="form" (ngSubmit)="saveAndContinue()">
        <div class="card-head">
          <div class="placeholder-copy">
            <div>
              <h2>Work Experience details</h2>
              <p>Your information is securely saved to your student profile.</p>
            </div>
          </div>
          <span class="step-badge">STEP 6 OF 9</span>
        </div>

        <h3 class="section-title">Do you have any work experience?</h3>
        <div class="toggle-group">
          <label class="toggle-option" [class.active]="workStatus==='Fresher'">
            <input type="radio" name="workStatus" value="Fresher" [checked]="workStatus==='Fresher'" (change)="onWorkStatusChange('Fresher')"> I am a Fresher
          </label>
          <label class="toggle-option" [class.active]="workStatus==='Yes'">
            <input type="radio" name="workStatus" value="Yes" [checked]="workStatus==='Yes'" (change)="onWorkStatusChange('Yes')"> Yes
          </label>
        </div>

        <div class="reveal-section" [class.open]="workStatus==='Yes'">
          <div class="dynamic-fields">
            <label [class.field-invalid]="showError('relevantYears')">
              <span class="field-label">Relevant Experience (Years) <span class="required-mark">*</span></span>
              <input type="number" min="0" formControlName="relevantYears" placeholder="e.g. 2" (blur)="markTouched('relevantYears')">
              <small class="field-error" *ngIf="showError('relevantYears')">Enter your relevant experience</small>
            </label>
            <label [class.field-invalid]="showError('nonRelevantYears')">
              <span class="field-label">Non-Relevant Experience (Years) <span class="required-mark">*</span></span>
              <input type="number" min="0" formControlName="nonRelevantYears" placeholder="e.g. 1" (blur)="markTouched('nonRelevantYears')">
              <small class="field-error" *ngIf="showError('nonRelevantYears')">Enter your non-relevant experience</small>
            </label>
          </div>

          <h3 class="section-title">Experience details</h3>
          <p class="section-hint">Add each job or internship — company, role and how long you were there.</p>

          <div class="experience-entry" *ngFor="let grp of experiencesArray.controls; let i=index" [formGroup]="asGroup(grp)">
            <div class="experience-entry-head">
              <strong>Experience {{i+1}}</strong>
              <button type="button" class="experience-remove" (click)="removeExperience(i)" aria-label="Remove experience">×</button>
            </div>
            <div class="dynamic-fields">
              <label [class.field-invalid]="showExpError(asGroup(grp),'companyName')">
                <span class="field-label">Company Name <span class="required-mark">*</span></span>
                <input type="text" formControlName="companyName" placeholder="e.g. Acme Corp" (blur)="markExpTouched(asGroup(grp),'companyName')">
                <small class="field-error" *ngIf="showExpError(asGroup(grp),'companyName')">Enter the company name</small>
              </label>
              <label [class.field-invalid]="showExpError(asGroup(grp),'role')">
                <span class="field-label">Role / Position <span class="required-mark">*</span></span>
                <input type="text" formControlName="role" placeholder="e.g. Software Engineering Intern" (blur)="markExpTouched(asGroup(grp),'role')">
                <small class="field-error" *ngIf="showExpError(asGroup(grp),'role')">Enter your role</small>
              </label>
              <label [class.field-invalid]="showExpError(asGroup(grp),'type')">
                <span class="field-label">Type <span class="required-mark">*</span></span>
                <select formControlName="type" (blur)="markExpTouched(asGroup(grp),'type')">
                  <option value="" disabled>Select type</option>
                  <option *ngFor="let t of employmentTypes" [value]="t">{{t}}</option>
                </select>
                <small class="field-error" *ngIf="showExpError(asGroup(grp),'type')">Select the experience type</small>
              </label>
              <label [class.field-invalid]="showExpError(asGroup(grp),'durationMonths')">
                <span class="field-label">Duration (Months) <span class="required-mark">*</span></span>
                <input type="number" min="0" formControlName="durationMonths" placeholder="e.g. 6" (blur)="markExpTouched(asGroup(grp),'durationMonths')">
                <small class="field-error" *ngIf="showExpError(asGroup(grp),'durationMonths')">Enter the duration</small>
              </label>
              <label class="wide">
                <span class="field-label">Description</span>
                <textarea formControlName="description" placeholder="What did you work on?"></textarea>
              </label>
            </div>
          </div>

          <button type="button" class="add-experience-btn" (click)="addExperience()">+ Add {{ experiencesArray.length ? 'another' : 'an' }} experience</button>
        </div>

        <p class="save-message error" *ngIf="submitted && form.invalid">Please fix the highlighted fields before continuing.</p>
        <p class="save-message error" *ngIf="saveError">{{saveError}}</p>
      </form>

      <div class="step-actions">
        <a class="button secondary" routerLink="/student/competitive-exam">Previous</a>
        <button class="button primary" type="button" [disabled]="saving" (click)="saveAndContinue()">{{saving ? 'Saving…' : 'Continue'}}</button>
      </div>
    </section>
  `
})
export class WorkExperienceComponent implements OnInit {
  submitted = false;
  employmentTypes: string[] = [];

  form = this.fb.nonNullable.group({
    workStatus: this.fb.nonNullable.control<string>(''),
    relevantYears: this.fb.nonNullable.control<string>(''),
    nonRelevantYears: this.fb.nonNullable.control<string>(''),
    experiences: this.fb.array<FormGroup>([])
  });

  saving = false;
  saveError = '';

  private returnToReview = false;

  constructor(
    private fb: FormBuilder,
    public store: StudentProfileUiStore,
    private router: Router,
    private route: ActivatedRoute,
    private api: AuthApiService,
    private cdr: ChangeDetectorRef
  ) {
    this.form.patchValue({
      workStatus: this.store.values['workStatus'] || '',
      relevantYears: this.store.values['relevantYears'] || '',
      nonRelevantYears: this.store.values['nonRelevantYears'] || ''
    });
    if (this.workStatus === 'Yes') {
      this.applyRelevantValidators(true);
      const saved = this.parseSavedExperiences();
      if (saved.length) saved.forEach(entry => this.addExperience(entry));
      else this.addExperience();
    }
    this.returnToReview = this.route.snapshot.queryParamMap.get('from') === 'review';
  }

  private parseSavedExperiences(): Record<string, string>[] {
    try {
      return JSON.parse(this.store.values['workExperiences'] || '[]');
    } catch {
      return [];
    }
  }

  private getToken(): string | null {
    return localStorage.getItem('superoffer_access_token') || sessionStorage.getItem('superoffer_access_token');
  }

  private handleUnauthorized() {
    localStorage.removeItem('superoffer_access_token');
    sessionStorage.removeItem('superoffer_access_token');
    this.router.navigate(['/auth/login/student'], { queryParams: { sessionExpired: '1' } });
  }

  /** Local store already hydrated the form synchronously; this only fills in from the
   *  server when the local store had nothing — e.g. a fresh browser/session. */
  async ngOnInit() {
    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }
    try {
      const options = await this.api.getWorkExperienceReferenceData();
      this.employmentTypes = options.employmentTypes;
    } catch {
      // Reference data endpoint unreachable — the type dropdown stays empty; existing selections still load below.
    }
    if (this.workStatus) {
      this.cdr.detectChanges();
      return;
    }
    try {
      const profile = await this.api.studentProfile(token);
      const work = (profile?.workExperience as Record<string, unknown>) || {};
      const status = (work['workStatus'] as string) || '';
      if (status) {
        this.form.patchValue({
          workStatus: status,
          relevantYears: (work['relevantYears'] as string) || '',
          nonRelevantYears: (work['nonRelevantYears'] as string) || ''
        });
        if (status === 'Yes') {
          this.applyRelevantValidators(true);
          const experiences = (work['experiences'] as Record<string, string>[]) || [];
          if (experiences.length) experiences.forEach(entry => this.addExperience(entry));
          else this.addExperience();
        }
      }
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        this.handleUnauthorized();
        return;
      }
      // No saved work experience yet, or the server is unreachable — the student can still fill the form from scratch.
    }
    this.cdr.detectChanges();
  }

  get experiencesArray(): FormArray { return this.form.get('experiences') as FormArray; }
  asGroup(control: AbstractControl): FormGroup { return control as FormGroup; }

  addExperience(entry?: Record<string, string>) {
    this.experiencesArray.push(this.fb.group({
      companyName: [entry?.['companyName'] || '', Validators.required],
      role: [entry?.['role'] || '', Validators.required],
      type: [entry?.['type'] || '', Validators.required],
      durationMonths: [entry?.['durationMonths'] || '', Validators.required],
      description: [entry?.['description'] || '']
    }));
  }

  removeExperience(index: number) { this.experiencesArray.removeAt(index); }

  markExpTouched(group: FormGroup, key: string) { group.get(key)!.markAsTouched(); }
  showExpError(group: FormGroup, key: string): boolean {
    const control = group.get(key)!;
    return (control.touched || this.submitted) && control.invalid;
  }

  get workStatus(): string { return this.form.get('workStatus')!.value; }

  private applyRelevantValidators(required: boolean) {
    const relevant = this.form.get('relevantYears')!;
    const nonRelevant = this.form.get('nonRelevantYears')!;
    relevant.setValidators(required ? Validators.required : null);
    nonRelevant.setValidators(required ? Validators.required : null);
    if (!required) {
      relevant.setValue('');
      nonRelevant.setValue('');
      relevant.markAsUntouched();
      nonRelevant.markAsUntouched();
    }
    relevant.updateValueAndValidity({ emitEvent: false });
    nonRelevant.updateValueAndValidity({ emitEvent: false });
  }

  onWorkStatusChange(value: string) {
    const control = this.form.get('workStatus')!;
    control.setValue(value);
    control.markAsTouched();
    this.applyRelevantValidators(value === 'Yes');
    if (value === 'Yes') {
      if (!this.experiencesArray.length) this.addExperience();
    } else {
      this.experiencesArray.clear();
    }
  }

  markTouched(key: string) { this.form.get(key)!.markAsTouched(); }
  showError(key: string): boolean {
    const control = this.form.get(key)!;
    return (control.touched || this.submitted) && control.invalid;
  }

  async saveAndContinue() {
    this.submitted = true;
    this.saveError = '';
    this.form.markAllAsTouched();
    if (this.form.invalid) return;

    const token = this.getToken();
    if (!token) {
      this.router.navigate(['/auth/login/student']);
      return;
    }

    const value = this.form.getRawValue();
    const first = value.experiences[0] as Record<string, string> | undefined;
    const companyName = first ? first['companyName'] : '';
    const jobRole = first ? first['role'] : '';

    this.saving = true;
    try {
      await this.api.saveStudentWorkExperience(token, {
        workStatus: value.workStatus || undefined,
        relevantYears: value.relevantYears || undefined,
        nonRelevantYears: value.nonRelevantYears || undefined,
        experiences: value.experiences,
        companyName,
        jobRole
      });

      this.store.values['workStatus'] = value.workStatus;
      this.store.values['relevantYears'] = value.relevantYears;
      this.store.values['nonRelevantYears'] = value.nonRelevantYears;
      this.store.values['workExperiences'] = JSON.stringify(value.experiences);
      this.store.values['companyName'] = companyName;
      this.store.values['jobRole'] = jobRole;

      this.router.navigateByUrl(this.returnToReview ? '/student/review' : '/student/financial-information');
    } catch (e) {
      if ((e as { status?: number }).status === 401) {
        this.handleUnauthorized();
        return;
      }
      this.saveError = e instanceof Error ? e.message : 'Could not save your work experience. Please try again.';
    } finally {
      this.saving = false;
      this.cdr.detectChanges();
    }
  }
}
